---帳務組客戶問題單
alter table TBBm12115 add column U_Chenshu2 varchar(100);

insert into TsField set FId='2eda0929-0c00-7f33-440c-17bc9958e730', FUnitId='c120fea7-0c5d-4c1f-9a0b-ac9802c13f88', FName='U_Chenshu2',          FTitle='服務項目2問題陳述',                                FType='ComboBox-Inputable',  FSize=100,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId='2eda0929-0c00-7f33-440c-17bc99393b50', FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,          FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=0, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,          FHint='',                           FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,          FMobileListFormat=null, FFollowingField=null, FParentField=null;
update TsField set FUnitId='c120fea7-0c5d-4c1f-9a0b-ac9802c13f88', FName='U_Notice',            FTitle='提醒事項',                                         FType='ComboBox-SelectOnly', FSize=100,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId='2eda0929-0c00-e911-cd02-179c6ee24040', FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,          FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=0, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue='0',           FHint='',                           FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,          FMobileListFormat=null, FFollowingField=null, FParentField=null where FId='2eda0929-0c00-e911-cd02-179c6eefc6e0';
java setFormFields('0186e900-0202-4dad-be4c-903dde81f747', '基本資訊', '22294c69-a635-4b82-82a8-4fff61509370', null, 'U_ErrorCode,U_ErrorMemo,F_Satisfy,U_PageCode,U_PageNum,U_PageStatus,FStatus', '聯絡人', 'cb89edfc-a4be-4f3a-97dc-4233b2411855', '22294c69-a635-4b82-82a8-4fff61509370', 'F_Identify,F_CardKind,F_Datetime,F_HomePhone,F_CompanyPhone,F_MobilePhone,F_UserName,F_CardNumber,F_Branch,U_CaseType', '服務資訊', '5549477e-d4f5-4233-98a3-a26fcc90f251', '22294c69-a635-4b82-82a8-4fff61509370', 'U_CutYM,U_DisCard1,U_DisCard2,U_DisCard3,U_DisCardAMT1,U_DisCardAMT2,U_DisCardAMT3,U_Notice,F_Year,F_BillMonth,U_AnnulThisYear,F_Jianmian,U_AnnulReason,U_Chenshu,F_Tuiyifukuan,F_Tuiyijin,F_Style,F_Zhanghu,F_Fenhang,F_BranchName,U_TransBankNo,U_TransBch,U_Chenshu2,F_Qx,F_Money,F_Reason,F_Other,F_Chenshu,U_Against,U_Describe', '舊欄位', '179cad6f-1e50-02cd-11e9-000c2909da2e', '22294c69-a635-4b82-82a8-4fff61509370', 'F_CutYM,F_Yearamount,F_Weiruzhang,F_Weijin,F_Jkrq,F_Fkh,F_Diaozhang,F_DMoney,F_Jian,F_JMoney,F_ReasonD,F_UserName1,F_CardNumber1,F_Address', '服務等級', '85e80690-0913-4855-9c50-e94f5b9b1f56', '22294c69-a635-4b82-82a8-4fff61509370', 'F_Importent,FUserId,F_DepartmentId,F_FinishTime,F_FormClose');



---利息違約金減免單
alter table TBBm12117 alter U_eFUNCardNotice set data type varchar(200);
update TsField set  FUnitId='cf948c0c-b80e-4f46-8fb7-cc47e6a9f9dd', FName='F_Lixi',              FTitle='利息調減金額',                 FType='InputBox-Text',       FSize=10,    FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,         FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,          FHint='',                           FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null, FMobileListFormat=null, FFollowingField=null, FParentField=null where FId='c5d0f812-9ca3-4f23-ab76-b634915ceac6';
update TsField set  FUnitId='cf948c0c-b80e-4f46-8fb7-cc47e6a9f9dd', FName='U_eFUNCardNotice',    FTitle='藝FUN卡博物館優惠說明',        FType='ComboBox-Inputable',  FSize=200,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId='2eda0929-0c00-be3e-6c06-1799d2ce9000', FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,         FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=0, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue='0',           FHint='',                           FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null, FMobileListFormat=null, FFollowingField=null, FParentField=null where FId='2eda0929-0c00-be3e-6c06-1799d2cf1bd0';
update TsField set  FUnitId='cf948c0c-b80e-4f46-8fb7-cc47e6a9f9dd', FName='U_SevItem1',          FTitle='服務項目1-違約金利息減免',     FType='CheckBox',            FSize=null,  FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,         FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,          FHint='',                           FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null, FMobileListFormat=null, FFollowingField=null, FParentField=null where FId='2eda0929-0c00-be3e-6c06-1798de5a9a00';
update TsField set  FUnitId='cf948c0c-b80e-4f46-8fb7-cc47e6a9f9dd', FName='U_SevType3',          FTitle='服務類型3',                    FType='RadioBox',            FSize=10,    FVisible=1, FFilterByRole=0, FRequired=1, FReadOnly=1, FQueryable=1, FDictionaryId='17800eb6-f930-003a-31c7-005056c00008', FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,         FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,          FHint='',                           FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null, FMobileListFormat=null, FFollowingField=null, FParentField=null where FId='2eda0929-0c00-be3e-6c06-179962f1f940';
update TsField set  FUnitId='cf948c0c-b80e-4f46-8fb7-cc47e6a9f9dd', FName='U_SevType4',          FTitle='服務類型4',                    FType='RadioBox',            FSize=20,    FVisible=1, FFilterByRole=0, FRequired=1, FReadOnly=1, FQueryable=1, FDictionaryId='17800dfd-48b0-003a-31c7-005056c00008', FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,         FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=1,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,          FHint='',                           FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null, FMobileListFormat=null, FFollowingField=null, FParentField=null where FId='2eda0929-0c00-be3e-6c06-1799d22718e0';

update TwVersion set FBusinessLogCode=null, FBusinessLogDescription=null, FDepartmentId=null, FDescription=null, FEntityEventCode=null,  FNotice='{"useDefaultTerminateMedia":true,"useDefaultWorkItemNotice":true,"useDefaultFinishNotice":true,"useDefaultWorkItemMedia":true,"useDefaultFinishMedia":true,"useDefaultTerminateNotice":true}', FReleaseTime=timestamp('2017-04-05 12:55:39'), FRelevantData='[]', FStatus='Expired', FVersion=32, FWorkflowId='5979bfc9-326b-42ad-8cd2-7894d54bfab8' where FId='83da3350-1b01-0218-4f7d-ffffff15b3c7';

insert into TwVersion set FBusinessLogCode=null, FBusinessLogDescription=null, FDepartmentId=null, FDescription='2021.09.03-gemfor/lillian-台企銀客服/催收二線->事件->活動建立後 更新實體 內容 修正', FEntityEventCode=null, FId='2eda0929-0c00-7c06-9009-17baafa6c4f0', FNotice='{"useDefaultFinishNotice":true,"useDefaultTerminateNotice":true,"useDefaultWorkItemNotice":true,"useDefaultFinishMedia":true,"useDefaultWorkItemMedia":true,"useDefaultTerminateMedia":true}', FReleaseTime=timestamp('2021-09-03 17:33:54'), FRelevantData='[]', FStatus='Active', FVersion=33, FWorkflowId='5979bfc9-326b-42ad-8cd2-7894d54bfab8';
insert into TwNode set FAutoCompleteMode='None', FAutoCompleteResult=null, FAutoCompleteTimeLength=null, FAutoCompleteTimeType=null, FAutoFinish=null, FBatchPassResult=null, FCode='AgentSign',  FDeputeHours=null, FDeputeMode='DefaultHours', FExpectedResult=null, FId='2eda0929-0c00-7c06-9009-17baafa78f30', FInstant=null, FJoinCondition='',   FJoinConditionType=null, FJoinMode='Single', FMultiWorkItem=0,    FName='臺企銀客服一線',         FPageLoadHandler=null, FParticipant='{"source":"Initiator"}',                                                                             FPrivilegeId=null, FSupportBatchPass=null, FSupportClone=0,    FSupportTransfer=0,    FType='Manual', FUrl=null, FUrlType='EntityInfo', FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0', FX=24, FY=7;
insert into TwNode set FAutoCompleteMode='None', FAutoCompleteResult=null, FAutoCompleteTimeLength=null, FAutoCompleteTimeType=null, FAutoFinish=null, FBatchPassResult=null, FCode='AgentSign1', FDeputeHours=null, FDeputeMode='DefaultHours', FExpectedResult=null, FId='2eda0929-0c00-7c06-9009-17baafa783a0', FInstant=null, FJoinCondition='',   FJoinConditionType=null, FJoinMode='Single', FMultiWorkItem=0,    FName='臺企銀客服一線退回修改', FPageLoadHandler=null, FParticipant='{"source":"Initiator"}',                                                                             FPrivilegeId=null, FSupportBatchPass=null, FSupportClone=0,    FSupportTransfer=0,    FType='Manual', FUrl=null, FUrlType='EntityInfo', FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0', FX=6,  FY=2;
insert into TwNode set FAutoCompleteMode='None', FAutoCompleteResult=null, FAutoCompleteTimeLength=null, FAutoCompleteTimeType=null, FAutoFinish=1,    FBatchPassResult=null, FCode='Agree',      FDeputeHours=null, FDeputeMode='DefaultHours', FExpectedResult=null, FId='2eda0929-0c00-7c06-9009-17baafa78b10', FInstant=null, FJoinCondition='',   FJoinConditionType=null, FJoinMode='Single', FMultiWorkItem=null, FName='同意',                   FPageLoadHandler=null, FParticipant=null,                                                                                                 FPrivilegeId=null, FSupportBatchPass=null, FSupportClone=null, FSupportTransfer=null, FType='Auto',   FUrl=null, FUrlType=null,         FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0', FX=6,  FY=12;
insert into TwNode set FAutoCompleteMode='None', FAutoCompleteResult=null, FAutoCompleteTimeLength=null, FAutoCompleteTimeType=null, FAutoFinish=1,    FBatchPassResult=null, FCode='Agree2',     FDeputeHours=null, FDeputeMode='DefaultHours', FExpectedResult=null, FId='2eda0929-0c00-7c06-9009-17baafa78c10', FInstant=null, FJoinCondition='',   FJoinConditionType=null, FJoinMode='Single', FMultiWorkItem=null, FName='作業科同意',             FPageLoadHandler=null, FParticipant=null,                                                                                                 FPrivilegeId=null, FSupportBatchPass=null, FSupportClone=null, FSupportTransfer=null, FType='Auto',   FUrl=null, FUrlType=null,         FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0', FX=17, FY=7;
insert into TwNode set FAutoCompleteMode='None', FAutoCompleteResult=null, FAutoCompleteTimeLength=null, FAutoCompleteTimeType=null, FAutoFinish=null, FBatchPassResult=null, FCode='Audit',      FDeputeHours=null, FDeputeMode='DefaultHours', FExpectedResult=null, FId='2eda0929-0c00-7c06-9009-17baafa6fde0', FInstant=0,    FJoinCondition='',   FJoinConditionType=null, FJoinMode='Single', FMultiWorkItem=0,    FName='臺企銀客服/催收二線',    FPageLoadHandler=null, FParticipant='{"source":"Sql","value":"select FUserId from TsRoleUser where FRoleId in (select case when TRU .FRoleId=''38B64561-5FB1-4A88-80DF-BEF8051E8DB7'' --催收一線ID\n                   then ''1C5A1FA7-9CF0-4AED-A98B-F1E65E73C28C''  --催收二線ID\n\t           when TRU .FRoleId=''EF283CDD-32D6-4FD5-AFB7-18FBEFB84766'' --客服一線ID\n                   then ''D1A4BD4E-87D0-4833-A596-5ADCDBEE4ABD'' --客服二線ID\n\t   End  as  FId\nfrom TsRoleUser as TRU\nwhere TRU.FUserId =${entity.F_CustomerId})"}', FPrivilegeId=null, FSupportBatchPass=0,    FSupportClone=1,    FSupportTransfer=1,    FType='Manual', FUrl=null, FUrlType='EntityInfo', FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0', FX=6,  FY=7;
insert into TwNode set FAutoCompleteMode='None', FAutoCompleteResult=null, FAutoCompleteTimeLength=null, FAutoCompleteTimeType=null, FAutoFinish=1,    FBatchPassResult=null, FCode='Back',       FDeputeHours=null, FDeputeMode='DefaultHours', FExpectedResult=null, FId='2eda0929-0c00-7c06-9009-17baafa78d10', FInstant=null, FJoinCondition='',   FJoinConditionType=null, FJoinMode='Single', FMultiWorkItem=null, FName='退回',                   FPageLoadHandler=null, FParticipant=null,                                                                                                 FPrivilegeId=null, FSupportBatchPass=null, FSupportClone=null, FSupportTransfer=null, FType='Auto',   FUrl=null, FUrlType=null,         FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0', FX=2,  FY=4;
insert into TwNode set FAutoCompleteMode='None', FAutoCompleteResult=null, FAutoCompleteTimeLength=null, FAutoCompleteTimeType=null, FAutoFinish=1,    FBatchPassResult=null, FCode='Back2',      FDeputeHours=null, FDeputeMode='DefaultHours', FExpectedResult=null, FId='2eda0929-0c00-7c06-9009-17baafa787e0', FInstant=null, FJoinCondition='',   FJoinConditionType=null, FJoinMode='Single', FMultiWorkItem=null, FName='作業科退回',             FPageLoadHandler=null, FParticipant=null,                                                                                                 FPrivilegeId=null, FSupportBatchPass=null, FSupportClone=null, FSupportTransfer=null, FType='Auto',   FUrl=null, FUrlType=null,         FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0', FX=10, FY=3;
insert into TwNode set FAutoCompleteMode=null,   FAutoCompleteResult=null, FAutoCompleteTimeLength=null, FAutoCompleteTimeType=null, FAutoFinish=null, FBatchPassResult=null, FCode='End',        FDeputeHours=null, FDeputeMode=null,           FExpectedResult=null, FId='2eda0929-0c00-7c06-9009-17baafa74850', FInstant=null, FJoinCondition='',   FJoinConditionType=null, FJoinMode='Single', FMultiWorkItem=null, FName='結案',                   FPageLoadHandler=null, FParticipant=null,                                                                                                 FPrivilegeId=null, FSupportBatchPass=null, FSupportClone=null, FSupportTransfer=null, FType='End',    FUrl=null, FUrlType=null,         FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0', FX=33, FY=7;
insert into TwNode set FAutoCompleteMode=null,   FAutoCompleteResult=null, FAutoCompleteTimeLength=null, FAutoCompleteTimeType=null, FAutoFinish=null, FBatchPassResult=null, FCode='End1',       FDeputeHours=null, FDeputeMode=null,           FExpectedResult=null, FId='2eda0929-0c00-7c06-9009-17baafa77780', FInstant=null, FJoinCondition='',   FJoinConditionType=null, FJoinMode='Single', FMultiWorkItem=null, FName='作廢',                   FPageLoadHandler=null, FParticipant=null,                                                                                                 FPrivilegeId=null, FSupportBatchPass=null, FSupportClone=null, FSupportTransfer=null, FType='End',    FUrl=null, FUrlType=null,         FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0', FX=33, FY=2;
insert into TwNode set FAutoCompleteMode='None', FAutoCompleteResult=null, FAutoCompleteTimeLength=null, FAutoCompleteTimeType=null, FAutoFinish=null, FBatchPassResult=null, FCode='H6901',      FDeputeHours=null, FDeputeMode='DefaultHours', FExpectedResult=null, FId='2eda0929-0c00-7c06-9009-17baafa77b60', FInstant=null, FJoinCondition='',   FJoinConditionType=null, FJoinMode='Single', FMultiWorkItem=0,    FName='臺企銀作業科人員',       FPageLoadHandler=null, FParticipant='{"source":"List","value":[{"text":"臺企銀作業科人員2","type":"Role","value":"8be1db89-0d84-49ea-8f99-85641f915917"}]}', FPrivilegeId=null, FSupportBatchPass=null, FSupportClone=0,    FSupportTransfer=0,    FType='Manual', FUrl=null, FUrlType='EntityInfo', FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0', FX=10, FY=7;
insert into TwNode set FAutoCompleteMode=null,   FAutoCompleteResult=null, FAutoCompleteTimeLength=null, FAutoCompleteTimeType=null, FAutoFinish=null, FBatchPassResult=null, FCode='Start',      FDeputeHours=null, FDeputeMode=null,           FExpectedResult=null, FId='2eda0929-0c00-7c06-9009-17baafa78a10', FInstant=null, FJoinCondition=null, FJoinConditionType=null, FJoinMode=null,     FMultiWorkItem=null, FName='開始',                   FPageLoadHandler=null, FParticipant=null,                                                                                                 FPrivilegeId=null, FSupportBatchPass=null, FSupportClone=null, FSupportTransfer=null, FType='Start',  FUrl=null, FUrlType=null,         FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0', FX=1,  FY=7;
insert into TwLine set FCode='LINE-1',  FCondition='',                                 FConditionType=null,         FDefault=1, FFrom='Start',      FId='2eda0929-0c00-7c06-9009-17baafa7ab40', FJumpResult=null, FName='提交', FRoutes=null,                  FSupportJump=0,    FTo='Audit',      FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0';
insert into TwLine set FCode='LINE-10', FCondition=null,                               FConditionType=null,         FDefault=1, FFrom='Back2',      FId='2eda0929-0c00-7c06-9009-17baafa7acd0', FJumpResult=null, FName=null,   FRoutes=null,                  FSupportJump=null, FTo='AgentSign1', FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0';
insert into TwLine set FCode='LINE-11', FCondition='',                                 FConditionType=null,         FDefault=1, FFrom='Agree2',     FId='2eda0929-0c00-7c06-9009-17baafa7a9d0', FJumpResult=null, FName='同意', FRoutes=null,                  FSupportJump=0,    FTo='AgentSign',  FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0';
insert into TwLine set FCode='LINE-12', FCondition='',                                 FConditionType=null,         FDefault=1, FFrom='Agree',      FId='2eda0929-0c00-7c06-9009-17baafa7ac50', FJumpResult=null, FName='同意', FRoutes='[{"x":336,"y":400}]', FSupportJump=0,    FTo='H6901',      FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0';
insert into TwLine set FCode='LINE-2',  FCondition='${AuditResult}=="Agree"',          FConditionType='JavaScript', FDefault=0, FFrom='Audit',      FId='2eda0929-0c00-7c06-9009-17baafa7aac0', FJumpResult=null, FName='同意', FRoutes=null,                  FSupportJump=0,    FTo='Agree',      FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0';
insert into TwLine set FCode='LINE-3',  FCondition='${AgentSign1Result}==''Submit''',  FConditionType='JavaScript', FDefault=0, FFrom='AgentSign1', FId='2eda0929-0c00-7c06-9009-17baafa7ade0', FJumpResult=null, FName='提交', FRoutes=null,                  FSupportJump=0,    FTo='Audit',      FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0';
insert into TwLine set FCode='LINE-4',  FCondition='${AuditResult}==''Back''',         FConditionType='JavaScript', FDefault=0, FFrom='Audit',      FId='2eda0929-0c00-7c06-9009-17baafa7ab90', FJumpResult=null, FName='打回', FRoutes=null,                  FSupportJump=0,    FTo='Back',       FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0';
insert into TwLine set FCode='LINE-5',  FCondition='${AgentSignResult} ==  ''Agree''', FConditionType='JavaScript', FDefault=0, FFrom='AgentSign',  FId='2eda0929-0c00-7c06-9009-17baafa7aa80', FJumpResult=null, FName='查核', FRoutes=null,                  FSupportJump=0,    FTo='End',        FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0';
insert into TwLine set FCode='LINE-6',  FCondition='${H6901Result}=="Agree"',          FConditionType='JavaScript', FDefault=0, FFrom='H6901',      FId='2eda0929-0c00-7c06-9009-17baafa7ad60', FJumpResult=null, FName='同意', FRoutes=null,                  FSupportJump=0,    FTo='Agree2',     FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0';
insert into TwLine set FCode='LINE-7',  FCondition='${AgentSign1Result}==''Discard''', FConditionType='JavaScript', FDefault=0, FFrom='AgentSign1', FId='2eda0929-0c00-7c06-9009-17baafa7a900', FJumpResult=null, FName='作廢', FRoutes=null,                  FSupportJump=0,    FTo='End1',       FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0';
insert into TwLine set FCode='LINE-8',  FCondition='${H6901Result}=="Back"',           FConditionType='JavaScript', FDefault=0, FFrom='H6901',      FId='2eda0929-0c00-7c06-9009-17baafa7ab10', FJumpResult=null, FName='打回', FRoutes=null,                  FSupportJump=0,    FTo='Back2',      FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0';
insert into TwLine set FCode='LINE-9',  FCondition='',                                 FConditionType=null,         FDefault=1, FFrom='Back',       FId='2eda0929-0c00-7c06-9009-17baafa7ac90', FJumpResult=null, FName='退回', FRoutes=null,                  FSupportJump=0,    FTo='AgentSign1', FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0';
insert into TwButton set FCode='Agree',   FCommentRequired=0, FEntityEventCode=null, FHandleType='Default', FIcon=null, FId='2eda0929-0c00-7c06-9009-17baafa720a0', FIndex=1, FName='同意', FNodeId='2eda0929-0c00-7c06-9009-17baafa6fde0', FPageId=null, FParentId=null, FSaveForm=null, FScript=null, FType='Button';
insert into TwButton set FCode='Back',    FCommentRequired=0, FEntityEventCode=null, FHandleType='Default', FIcon=null, FId='2eda0929-0c00-7c06-9009-17baafa721a0', FIndex=2, FName='打回', FNodeId='2eda0929-0c00-7c06-9009-17baafa6fde0', FPageId=null, FParentId=null, FSaveForm=null, FScript=null, FType='Button';
insert into TwButton set FCode='Agree',   FCommentRequired=0, FEntityEventCode=null, FHandleType='Default', FIcon=null, FId='2eda0929-0c00-7c06-9009-17baafa78190', FIndex=1, FName='同意', FNodeId='2eda0929-0c00-7c06-9009-17baafa77b60', FPageId=null, FParentId=null, FSaveForm=null, FScript=null, FType='Button';
insert into TwButton set FCode='Back',    FCommentRequired=0, FEntityEventCode=null, FHandleType='Default', FIcon=null, FId='2eda0929-0c00-7c06-9009-17baafa781e0', FIndex=2, FName='打回', FNodeId='2eda0929-0c00-7c06-9009-17baafa77b60', FPageId=null, FParentId=null, FSaveForm=null, FScript=null, FType='Button';
insert into TwButton set FCode='Submit',  FCommentRequired=0, FEntityEventCode=null, FHandleType='Default', FIcon=null, FId='2eda0929-0c00-7c06-9009-17baafa784c0', FIndex=1, FName='提交', FNodeId='2eda0929-0c00-7c06-9009-17baafa783a0', FPageId=null, FParentId=null, FSaveForm=null, FScript=null, FType='Button';
insert into TwButton set FCode='Discard', FCommentRequired=0, FEntityEventCode=null, FHandleType='Default', FIcon=null, FId='2eda0929-0c00-7c06-9009-17baafa78530', FIndex=2, FName='作廢', FNodeId='2eda0929-0c00-7c06-9009-17baafa783a0', FPageId=null, FParentId=null, FSaveForm=null, FScript=null, FType='Button';
insert into TwButton set FCode='Agree',   FCommentRequired=0, FEntityEventCode=null, FHandleType='Default', FIcon=null, FId='2eda0929-0c00-7c06-9009-17baafa79050', FIndex=1, FName='同意', FNodeId='2eda0929-0c00-7c06-9009-17baafa78f30', FPageId=null, FParentId=null, FSaveForm=null, FScript=null, FType='Button';
insert into TwEvent set FContent='{FStatus:"New"}',               FEntityEventCode=null, FHandleType='UpdateEntity', FId='2eda0929-0c00-7c06-9009-17baafa7cad0', FIndex=1, FNodeId=null,                                   FNoticeId=null,                                   FNoticeRecipients='[]',                                                                                    FOccasion='OnProcessTerminateAfter', FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0';
insert into TwEvent set FContent='{FStatus:"Audit"}',             FEntityEventCode=null, FHandleType='UpdateEntity', FId='2eda0929-0c00-7c06-9009-17baafa743e0', FIndex=1, FNodeId='2eda0929-0c00-7c06-9009-17baafa6fde0', FNoticeId=null,                                   FNoticeRecipients='[]',                                                                                    FOccasion='OnActivityCreateAfter',   FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0';
insert into TwEvent set FContent='{"End'',F_CloseTime:"${now}"}', FEntityEventCode=null, FHandleType='UpdateEntity', FId='2eda0929-0c00-7c06-9009-17baafa776e0', FIndex=1, FNodeId='2eda0929-0c00-7c06-9009-17baafa74850', FNoticeId=null,                                   FNoticeRecipients='[]',                                                                                    FOccasion='OnActivityFinishAfter',   FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0';
insert into TwEvent set FContent='{"END1"}',                      FEntityEventCode=null, FHandleType='UpdateEntity', FId='2eda0929-0c00-7c06-9009-17baafa77b20', FIndex=1, FNodeId='2eda0929-0c00-7c06-9009-17baafa77780', FNoticeId=null,                                   FNoticeRecipients='[]',                                                                                    FOccasion='OnActivityCreateAfter',   FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0';
insert into TwEvent set FContent='{FStatus:"Audit3"}',            FEntityEventCode=null, FHandleType='UpdateEntity', FId='2eda0929-0c00-7c06-9009-17baafa78330', FIndex=1, FNodeId='2eda0929-0c00-7c06-9009-17baafa77b60', FNoticeId=null,                                   FNoticeRecipients='[]',                                                                                    FOccasion='OnActivityCreateAfter',   FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0';
insert into TwEvent set FContent='{FStatus:"AgentSign1"}',        FEntityEventCode=null, FHandleType='UpdateEntity', FId='2eda0929-0c00-7c06-9009-17baafa787a0', FIndex=1, FNodeId='2eda0929-0c00-7c06-9009-17baafa783a0', FNoticeId=null,                                   FNoticeRecipients='[]',                                                                                    FOccasion='OnActivityCreateAfter',   FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0';
insert into TwEvent set FContent='',                              FEntityEventCode=null, FHandleType='SendNotice',   FId='2eda0929-0c00-7c06-9009-17baafa789a0', FIndex=1, FNodeId='2eda0929-0c00-7c06-9009-17baafa787e0', FNoticeId='e0f0bc6d-cac4-4790-85a3-20fd2f9d54e7', FNoticeRecipients='[{"type":"Initiator"}]',                                                                FOccasion='OnActivityCreateAfter',   FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0';
insert into TwEvent set FContent='',                              FEntityEventCode=null, FHandleType='SendNotice',   FId='2eda0929-0c00-7c06-9009-17baafa78be0', FIndex=1, FNodeId='2eda0929-0c00-7c06-9009-17baafa78b10', FNoticeId='56ada4ed-2c26-4cb7-956b-1b17e0750d8f', FNoticeRecipients='[{"type":"Initiator"},{"type":"Role","value":"bc5fab26-3887-4d6d-b81c-380e04cf1b06"}]', FOccasion='OnActivityCreateAfter',   FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0';
insert into TwEvent set FContent='',                              FEntityEventCode=null, FHandleType='SendNotice',   FId='2eda0929-0c00-7c06-9009-17baafa78cd0', FIndex=1, FNodeId='2eda0929-0c00-7c06-9009-17baafa78c10', FNoticeId='7302e5ca-fdbc-4e20-b379-3e3c8316d831', FNoticeRecipients='[{"type":"Initiator"}]',                                                                FOccasion='OnActivityCreateAfter',   FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0';
insert into TwEvent set FContent='',                              FEntityEventCode=null, FHandleType='SendNotice',   FId='2eda0929-0c00-7c06-9009-17baafa78eb0', FIndex=1, FNodeId='2eda0929-0c00-7c06-9009-17baafa78d10', FNoticeId='fc3d9fd3-ee2a-4970-9def-e4641a9a2c9e', FNoticeRecipients='[{"type":"Initiator"}]',                                                                FOccasion='OnActivityCreateAfter',   FVersionId='2eda0929-0c00-7c06-9009-17baafa6c4f0';

