----------------------------------------------------金融卡發卡主檔-----------------------------------------------------------------------------------------

ALTER TABLE tpTBBUATMCardDetail ALTER column U_ACNO set data type varchar(11);
update  TsField set  FUnitId='2eda0929-0c00-8f3a-bb07-179eabb6da30', FName='U_ACNO',          FTitle='帳號',                        FType='InputBox-Text',       FSize=11,    FVisible=1, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',                            FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null, FMobileListFormat=null, FFollowingField=null, FParentField=null where FId='2eda0929-0c00-e960-be0e-179ef7e04250';



----------------------------------------------------信用卡已出總帳單明細查詢-----------------------------------------------------------------------------------------

update  TsField set  FUnitId='2eda0929-0c00-832b-5c0c-17a138ac4b90', FName='U_PageNum',          FTitle='TXNID',                      FType='InputBox-Text', FSize=10,    FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue='BSB1,BSB2', FHint='',     FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null, FMobileListFormat=null, FFollowingField=null, FParentField=null where FId='2eda0929-0c00-832b-5c0c-17a1396477f0';





----------------------------------------------------信用卡利息計算方式查詢-----------------------------------------------------------------------------------------
ALTER TABLE tpTBBUCardinterestcalculation ALTER column U_Stmtno set data type varchar(3);
alter table tpTBBUCardinterestcalculation add   U_Intabreakdte varchar(20);

insert into TsField set FId='2eda0929-0c00-a201-820d-17aa81033c70', FUnitId='2eda0929-0c00-2477-180e-17a1d9e63b40', FName='U_Intabreakdte',    FTitle='開始計算利息之日期',         FType='InputBox-Text', FSize=20,    FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,        FHint='',     FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null, FMobileListFormat=null, FFollowingField=null, FParentField=null;

update TsField set  FUnitId='2eda0929-0c00-2477-180e-17a1d9e63b40', FName='U_Revolvingrate',   FTitle='消費循環利率',               FType='InputBox-Text', FSize=20,    FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=1,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,        FHint='',     FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null, FMobileListFormat=null, FFollowingField=null, FParentField=null where FId='2eda0929-0c00-2501-430d-17a1e3561f30';
update TsField set  FUnitId='2eda0929-0c00-2477-180e-17a1d9e63b40', FName='U_Stmtno',          FTitle='帳單編號',                   FType='InputBox-Text', FSize=3,     FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=1,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,        FHint='',     FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null, FMobileListFormat=null, FFollowingField=null, FParentField=null where FId='2eda0929-0c00-2501-430d-17a1db9f7120';

update TsFieldGridColumn set  FFieldId='2eda0929-0c00-2501-430d-17a1e3619030', FTitle='帳單日期',                               FKey='U_Stmtdate',              FType='String',  FIndex=1,   FControls='' where FId='2eda0929-0c00-2501-430d-17a1e36f86e0';
update TsFieldGridColumn set  FFieldId='2eda0929-0c00-2501-430d-17a1e3619030', FTitle='查詢',                                   FKey='U_Button',                FType='Control', FIndex=3,   FControls='[{
    type: "Button",
    text: "查詢",
    onclick: "UCardinterestcalculationForm.doBDS2()"
}]' where FId='2eda0929-0c00-2501-430d-17a1e3802990';

insert into TsFieldGridColumn set FId='2eda0929-0c00-a201-820d-17aa812a59c0', FFieldId='2eda0929-0c00-2501-430d-17a1e3619030', FTitle='帳單編號',                               FKey='U_STMNNO',                FType='String',  FIndex=2,   FControls='';

java setFormFields('2eda0929-0c00-2477-180e-17a1d9e72150', '基本資訊', '2eda0929-0c00-2477-180e-17a1d9e72810', null, 'U_PageNum,U_ErrorCode,U_ErrorMemo,U_ErrorCode2,U_ErrorMemo2,U_CardNum,U_CardType,U_Stmtno,U_Inquiry', '查詢結果', '17a1e3d1-5950-0d43-0125-000c2909da2e', '2eda0929-0c00-2477-180e-17a1d9e72810', 'U_Grid,U_OCardNum,U_OCardType,U_Checkoutdate,U_Intabreakdte,U_Revolvingrate,U_Cashadvancerate,U_Grid2');



----------------------------------------------------風管科客戶問題單-----------------------------------------------------------------------------------------

update TsField set  FUnitId='4cbd7598-5cca-4891-8455-1c85f03f33c6', FName='F_StateProb',          FTitle='問題陳述區（500字以内）',                          FType='TextBox',             FSize=2000,  FVisible=1, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,              FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=3, FRowSpan=5, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,          FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null ,      FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,          FMobileListFormat=null, FFollowingField=null, FParentField=null	where FId='4fb897cb-6b42-4788-bd2a-44dbd5ca6b46';
update TsField set  FUnitId='4cbd7598-5cca-4891-8455-1c85f03f33c6', FName='F_ResultCode',         FTitle='風控人員處理結果（500字以内）',                    FType='TextBox',             FSize=1000,  FVisible=1, FFilterByRole=0, FRequired=1, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,              FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=3, FRowSpan=5, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,          FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null ,     FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,          FMobileListFormat=null, FFollowingField=null, FParentField=null	where FId='1c8bb6b7-b4b5-4604-a41e-421dc52b7361';

insert into TsPage set FId='2eda0929-0c00-f92d-f605-17aa90ce1840', FName='風管科客戶問題單',               FTitle='風管科客戶問題單',     FCode='TBB.m12114A_20210715.Report', FPlatform='Computer', FType='Other',      FIcon='quicksilver/image/unit/05.png',          FUrl='custom/tbb/page/m12114A_20210715.jsp',         FActionMethodName=null,                                FLoadHandler='m12114A_20210715_Report.doLoad', FRelationId=null, FUnitId='4cbd7598-5cca-4891-8455-1c85f03f33c6', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FDialogWidth=null, FDialogHeight=null, FHasViewFrame=0,    FQueryOnLoad=null, FQuerySchemaId=null, FQueryFormAutoQuery=0, FVisible=1, FDescription='',   FDialogMaximized=0,    FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments='',   FVisibleCondition=null, FEditId='4e9b96a5-4c20-42a0-8929-d83efc27af4e', FFormColumnCount=null;

insert into TsScript set FId='2eda0929-0c00-f92d-f605-17aa90e22c10', FIndex=1, FPageId='2eda0929-0c00-f92d-f605-17aa90ce1840', FUrl='custom/tbb/page/js/Common.js';
insert into TsScript set FId='2eda0929-0c00-f92d-f605-17aa90e23690', FIndex=2, FPageId='2eda0929-0c00-f92d-f605-17aa90ce1840', FUrl='custom/tbb/page/js/m12114A_20210715_Report.js';
insert into TsToolItem set FId='2eda0929-0c00-f92d-f605-17aa90d2c050', FPageId='2eda0929-0c00-f92d-f605-17aa90ce1840', FCode='Sure', FName='確定', FHint=null, FLabel=null, FType='Button', FAlign='right', FIndex=1, FWidth=null, FIcon=null, FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine='', FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='m12114A_20210715_Report.doPrint', FChartId=null;

insert into TsToolItem set FId='2eda0929-0c00-f92d-f605-17aa9203eea0', FPageId='62ea703c-d1b5-4f18-9a8e-023c401bfa8f', FCode='PrintNew', FName='列印(新)',     FHint=null, FLabel=null, FType='Button',      FAlign='right', FIndex=8, FWidth=null, FIcon='quicksilver/image/16/Print.png',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine='',   FVisibleCondition=null, FEnableCondition=null,                                                                             FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='m12114A.doOpenNew',    FChartId=null;

update TsToolItem set  FPageId='62ea703c-d1b5-4f18-9a8e-023c401bfa8f', FCode='Print',    FName='列印(舊)',     FHint=null, FLabel=null, FType='Button',      FAlign='right', FIndex=7, FWidth=null, FIcon='quicksilver/image/16/Print.png',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine='',   FVisibleCondition=null, FEnableCondition=null,                                                                             FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='m12114A.doOpen',       FChartId=null where FId='432e79af-2996-464b-bc65-51229da465a6';
update TsToolItem set  FPageId='62ea703c-d1b5-4f18-9a8e-023c401bfa8f', FCode='Other',    FName=null,           FHint=null, FLabel=null, FType='ComboButton', FAlign='right', FIndex=9, FWidth=0,    FIcon='quicksilver/image/16/Other.png',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource='SubItemTable', FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null,                                                                             FHandleType='None',       FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler=null,                   FChartId=null where FId='0b71553f-0b48-4b81-ad0f-e2c46ce96bb8';


----------------------------------------------------帳務組客戶問題單-----------------------------------------------------------------------------------------
update TsField set  FUnitId='c120fea7-0c5d-4c1f-9a0b-ac9802c13f88', FName='F_Chenshu',           FTitle='服務項目4問題陳述(300字以內)',                     FType='TextBox',             FSize=2000,  FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,          FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=3, FRowSpan=5, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,          FHint='',                           FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,          FMobileListFormat=null, FFollowingField=null, FParentField=null where FId='3459eec2-959b-4c02-ba65-d4e45da307dc';
update TsField set  FUnitId='c120fea7-0c5d-4c1f-9a0b-ac9802c13f88', FName='F_CutYM',             FTitle='(舊)服務項目1',                                    FType='MultiCheckBox',       FSize=10,    FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId='fc06fa82-2259-4a6d-9ea2-fc45dd86d35e', FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable='Tp01',        FRelationCapacity=10,   FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,          FHint='',                           FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,          FMobileListFormat=null, FFollowingField=null, FParentField=null where FId='8bd5d516-8c38-4024-b87b-04ed0a041cb5';
update TsField set  FUnitId='c120fea7-0c5d-4c1f-9a0b-ac9802c13f88', FName='F_Diaozhang',         FTitle='服務項目5',                                        FType='MultiCheckBox',       FSize=10,    FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId='3bf72ae7-c421-4e79-bfd5-7c181df1774d', FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable='Tp05',        FRelationCapacity=10,   FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=1,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,          FHint='',                           FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,          FMobileListFormat=null, FFollowingField=null, FParentField=null where FId='1c4102ed-1970-44f7-b962-04dca079a555';
update TsField set  FUnitId='c120fea7-0c5d-4c1f-9a0b-ac9802c13f88', FName='F_Jian',              FTitle='服務項目6',                                        FType='MultiCheckBox',       FSize=10,    FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId='b05072be-0ba8-498c-a8a4-7da0a3569987', FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable='Tp06',        FRelationCapacity=10,   FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=1,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,          FHint='',                           FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,          FMobileListFormat=null, FFollowingField=null, FParentField=null where FId='d7fe5756-bcad-40f7-84ca-c453fa682045';
update TsField set  FUnitId='c120fea7-0c5d-4c1f-9a0b-ac9802c13f88', FName='F_Weiruzhang',        FTitle='服務項目3',                                        FType='MultiCheckBox',       FSize=10,    FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId='bd569a6f-1e92-4f28-aeab-3610e4b4b787', FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable='Tp03',        FRelationCapacity=10,   FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=1,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,          FHint='',                           FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,          FMobileListFormat=null, FFollowingField=null, FParentField=null where FId='19c17b9b-65ce-4b31-880f-a3e367f16c08';
update TsField set  FUnitId='c120fea7-0c5d-4c1f-9a0b-ac9802c13f88', FName='F_Yearamount',        FTitle='年費金額',                                         FType='InputBox-BigInt',     FSize=null,  FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,          FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,          FHint='',                           FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,          FMobileListFormat=null, FFollowingField=null, FParentField=null where FId='236c58ff-fd47-402b-bbe1-d00797d1ed71';
update TsField set  FUnitId='c120fea7-0c5d-4c1f-9a0b-ac9802c13f88', FName='U_Chenshu',           FTitle='服務項目1問題陳述(300字以內)',                     FType='TextBox',             FSize=2000,  FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,          FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=0, FRowSpan=3, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,          FHint='',                           FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,          FMobileListFormat=null, FFollowingField=null, FParentField=null where FId='2eda0929-0c00-e911-cd02-179cb6d0b580';



----------------------------------------------------帳務組客戶問題單-----------------------------------------------------------------------------------------
insert into TsRolePrivilege set FExpression='', FGlobal=1, FId='bc3f335c-3a49-4a9b-a45c-e233df371096', FOperator='', FPrivilegeId='e6566429-7f28-47ba-aef1-d2660ae4b97e', FRoleId='8be1db89-0d84-49ea-8f99-85641f915917', FSql='';









