
-- TsMenu 
insert into TsMenu set FAlwaysOpenNewTab=0,    FArguments='',              FCountJavaClass=null, FCountStatus1=null,        FCountStatus2=null,   FCountStatus3=null,       FCountStatus4=null,       FCountStatusField=null,      FCountType=null,    FCountUnitId=null,                                   FCountUserField=null,            FEnabled=1, FEncrypt=0,    FExternalPageUrl=null, FFunctionName=null,                                                                                             FIcon='quicksilver/image/unit/01.png',             FId='c8abc4dd-d210-4b96-bf77-328f559546c1', FIndex=3,  FLicensed=1, FName='台企銀',                          FOpenMode=null,  FPageId='030e643a-abe7-4ab7-9e24-527b4bb3df17', FParentId='00000000-0000-0000-0008-020000000000', FQueryFormHidden=0,    FQuerySchemaId=null,                                   FQuerySchemaLocked=0,    FReplaceByChildren=0, FSubMenuRoutine='',   FSubMenuSource='MenuTable', FTabTitle=null,              FTabTitleSource='MenuName',  FTreeLevel=2, FTreeSerial='002.003',             FType='InternalPage';
insert into TsMenu set FAlwaysOpenNewTab=0,    FArguments='',              FCountJavaClass=null, FCountStatus1=null,        FCountStatus2=null,   FCountStatus3=null,       FCountStatus4=null,       FCountStatusField=null,      FCountType=null,    FCountUnitId=null,                                   FCountUserField=null,            FEnabled=1, FEncrypt=0,    FExternalPageUrl=null, FFunctionName='window.open("https://www.credit-aid.fisc.com.tw/ccard/(dxirkl55oz5uk445tbryswqq)/index.aspx");', FIcon='custom/tbb/image/form.png',                 FId='545ee76a-8bbd-4f5c-a867-ad3864d1903a', FIndex=1,  FLicensed=1, FName='(1)信用卡清算網站查詢及報表管理', FOpenMode=null,  FPageId=null,                                   FParentId='ae3dbc83-34fb-464b-ba4b-5607e746c98e', FQueryFormHidden=0,    FQuerySchemaId=null,                                   FQuerySchemaLocked=0,    FReplaceByChildren=0, FSubMenuRoutine='',   FSubMenuSource='MenuTable', FTabTitle=null,              FTabTitleSource='PageTitle', FTreeLevel=4, FTreeSerial='002.003.022.001',     FType='Function';
insert into TsMenu set FAlwaysOpenNewTab=0,    FArguments='',              FCountJavaClass=null, FCountStatus1=null,        FCountStatus2=null,   FCountStatus3=null,       FCountStatus4=null,       FCountStatusField=null,      FCountType=null,    FCountUnitId=null,                                   FCountUserField=null,            FEnabled=1, FEncrypt=0,    FExternalPageUrl=null, FFunctionName='window.open("https://www.acs3d.fisc.com.tw/FISCACS/main");',                                     FIcon='custom/tbb/image/keyandlock.png',           FId='ff782c91-facf-41ee-8433-c207641407d4', FIndex=2,  FLicensed=1, FName='(2)信用卡安全驗證系統',           FOpenMode=null,  FPageId=null,                                   FParentId='ae3dbc83-34fb-464b-ba4b-5607e746c98e', FQueryFormHidden=0,    FQuerySchemaId=null,                                   FQuerySchemaLocked=0,    FReplaceByChildren=0, FSubMenuRoutine='',   FSubMenuSource='MenuTable', FTabTitle=null,              FTabTitleSource='PageTitle', FTreeLevel=4, FTreeSerial='002.003.022.002',     FType='Function';
insert into TsMenu set FAlwaysOpenNewTab=0,    FArguments='',              FCountJavaClass=null, FCountStatus1=null,        FCountStatus2=null,   FCountStatus3=null,       FCountStatus4=null,       FCountStatusField=null,      FCountType=null,    FCountUnitId=null,                                   FCountUserField=null,            FEnabled=1, FEncrypt=0,    FExternalPageUrl=null, FFunctionName='window.open("https://eloanp.tbb.com.tw/TBBEL/ELINDEX.NSF?Open");',                               FIcon='custom/tbb/image/System_Preferences.png',   FId='76415cb3-fc4a-4af7-8ece-ea23bdacd8a1', FIndex=3,  FLicensed=1, FName='(3)徵授信及擔保品管理系統',       FOpenMode=null,  FPageId=null,                                   FParentId='ae3dbc83-34fb-464b-ba4b-5607e746c98e', FQueryFormHidden=0,    FQuerySchemaId=null,                                   FQuerySchemaLocked=0,    FReplaceByChildren=0, FSubMenuRoutine='',   FSubMenuSource='MenuTable', FTabTitle=null,              FTabTitleSource='PageTitle', FTreeLevel=4, FTreeSerial='002.003.022.003',     FType='Function';
insert into TsMenu set FAlwaysOpenNewTab=0,    FArguments='',              FCountJavaClass=null, FCountStatus1=null,        FCountStatus2=null,   FCountStatus3=null,       FCountStatus4=null,       FCountStatusField=null,      FCountType=null,    FCountUnitId=null,                                   FCountUserField=null,            FEnabled=1, FEncrypt=0,    FExternalPageUrl=null, FFunctionName='window.open("https://172.25.205.205/fweb/login.php");',                                          FIcon='custom/tbb/image/dollar_settings.png',      FId='84e5aa6d-782f-4956-8568-0e87d3e1d573', FIndex=4,  FLicensed=1, FName='(4)財金公司發卡授權共用處理系統', FOpenMode=null,  FPageId=null,                                   FParentId='ae3dbc83-34fb-464b-ba4b-5607e746c98e', FQueryFormHidden=0,    FQuerySchemaId=null,                                   FQuerySchemaLocked=0,    FReplaceByChildren=0, FSubMenuRoutine='',   FSubMenuSource='MenuTable', FTabTitle=null,              FTabTitleSource='PageTitle', FTreeLevel=4, FTreeSerial='002.003.022.004',     FType='Function';
insert into TsMenu set FAlwaysOpenNewTab=0,    FArguments='',              FCountJavaClass=null, FCountStatus1=null,        FCountStatus2=null,   FCountStatus3=null,       FCountStatus4=null,       FCountStatusField=null,      FCountType=null,    FCountUnitId=null,                                   FCountUserField=null,            FEnabled=1, FEncrypt=0,    FExternalPageUrl=null, FFunctionName='window.open("https://www.tbb.com.tw/web/guest/-82");',                                           FIcon='quicksilver/image/unit/New.gif',            FId='83da338f-2cd2-0048-598c-ffffff16bd44', FIndex=5,  FLicensed=1, FName='(5)新台幣存款利率',               FOpenMode=null,  FPageId=null,                                   FParentId='ae3dbc83-34fb-464b-ba4b-5607e746c98e', FQueryFormHidden=0,    FQuerySchemaId=null,                                   FQuerySchemaLocked=0,    FReplaceByChildren=0, FSubMenuRoutine='',   FSubMenuSource='MenuTable', FTabTitle=null,              FTabTitleSource='PageTitle', FTreeLevel=4, FTreeSerial='002.003.022.005',     FType='Function';
insert into TsMenu set FAlwaysOpenNewTab=0,    FArguments='',              FCountJavaClass=null, FCountStatus1=null,        FCountStatus2=null,   FCountStatus3=null,       FCountStatus4=null,       FCountStatusField=null,      FCountType=null,    FCountUnitId=null,                                   FCountUserField=null,            FEnabled=1, FEncrypt=0,    FExternalPageUrl=null, FFunctionName='window.open("https://www.tbb.com.tw/web/guest/-84");',                                           FIcon='quicksilver/image/unit/New.gif',            FId='83da338f-2cd2-0070-169a-ffffff16bd44', FIndex=6,  FLicensed=1, FName='(6)外幣存款率',                   FOpenMode=null,  FPageId=null,                                   FParentId='ae3dbc83-34fb-464b-ba4b-5607e746c98e', FQueryFormHidden=0,    FQuerySchemaId=null,                                   FQuerySchemaLocked=0,    FReplaceByChildren=0, FSubMenuRoutine='',   FSubMenuSource='MenuTable', FTabTitle=null,              FTabTitleSource='PageTitle', FTreeLevel=4, FTreeSerial='002.003.022.006',     FType='Function';
insert into TsMenu set FAlwaysOpenNewTab=0,    FArguments='',              FCountJavaClass=null, FCountStatus1=null,        FCountStatus2=null,   FCountStatus3=null,       FCountStatus4=null,       FCountStatusField=null,      FCountType=null,    FCountUnitId=null,                                   FCountUserField=null,            FEnabled=1, FEncrypt=0,    FExternalPageUrl=null, FFunctionName='window.open("https://www.tbb.com.tw/web/guest/exchange_rate");',                                 FIcon='quicksilver/image/unit/New.gif',            FId='83da338f-2cd2-0018-fd9f-ffffff16bd44', FIndex=7,  FLicensed=1, FName='(7)外匯匯率',                     FOpenMode=null,  FPageId=null,                                   FParentId='ae3dbc83-34fb-464b-ba4b-5607e746c98e', FQueryFormHidden=0,    FQuerySchemaId=null,                                   FQuerySchemaLocked=0,    FReplaceByChildren=0, FSubMenuRoutine='',   FSubMenuSource='MenuTable', FTabTitle=null,              FTabTitleSource='PageTitle', FTreeLevel=4, FTreeSerial='002.003.022.007',     FType='Function';
insert into TsMenu set FAlwaysOpenNewTab=1,    FArguments='',              FCountJavaClass=null, FCountStatus1=null,        FCountStatus2=null,   FCountStatus3=null,       FCountStatus4=null,       FCountStatusField=null,      FCountType=null,    FCountUnitId=null,                                   FCountUserField=null,            FEnabled=1, FEncrypt=0,    FExternalPageUrl=null, FFunctionName='window.open("http://10.11.20.84/");',                                                            FIcon='custom/tbb/image/dollar_settings.png',      FId='83da337a-4be6-0658-db5c-ffffff15b5c3', FIndex=23, FLicensed=1, FName='音檔調閱',                        FOpenMode=null,  FPageId=null,                                   FParentId='c8abc4dd-d210-4b96-bf77-328f559546c1', FQueryFormHidden=0,    FQuerySchemaId=null,                                   FQuerySchemaLocked=0,    FReplaceByChildren=0, FSubMenuRoutine='',   FSubMenuSource='MenuTable', FTabTitle=null,              FTabTitleSource='PageTitle', FTreeLevel=3, FTreeSerial='002.003.023',         FType='Function';
insert into TsMenu set FAlwaysOpenNewTab=1,    FArguments='',              FCountJavaClass=null, FCountStatus1=null,        FCountStatus2=null,   FCountStatus3=null,       FCountStatus4=null,       FCountStatusField=null,      FCountType=null,    FCountUnitId=null,                                   FCountUserField=null,            FEnabled=1, FEncrypt=0,    FExternalPageUrl=null, FFunctionName='window.open("http://10.11.20.92/TBB_Report/Default.aspx")',                                      FIcon=null,                                        FId='83da3347-6f04-0338-dcba-ffffff15bfb3', FIndex=24, FLicensed=1, FName='活動代碼報表',                    FOpenMode=null,  FPageId=null,                                   FParentId='c8abc4dd-d210-4b96-bf77-328f559546c1', FQueryFormHidden=0,    FQuerySchemaId=null,                                   FQuerySchemaLocked=0,    FReplaceByChildren=0, FSubMenuRoutine='',   FSubMenuSource='MenuTable', FTabTitle=null,              FTabTitleSource='PageTitle', FTreeLevel=3, FTreeSerial='002.003.024',         FType='Function';
insert into TsMenu set FAlwaysOpenNewTab=0,    FArguments='',              FCountJavaClass=null, FCountStatus1=null,        FCountStatus2=null,   FCountStatus3=null,       FCountStatus4=null,       FCountStatusField=null,      FCountType=null,    FCountUnitId=null,                                   FCountUserField=null,            FEnabled=1, FEncrypt=0,    FExternalPageUrl=null, FFunctionName='window.open("http://10.11.20.92/TBB_Report/MemberAcReport.aspx")',                               FIcon=null,                                        FId='83da3347-6f04-0310-c2c7-ffffff15bfb3', FIndex=25, FLicensed=1, FName='客服人員-活動代碼報表',           FOpenMode=null,  FPageId=null,                                   FParentId='c8abc4dd-d210-4b96-bf77-328f559546c1', FQueryFormHidden=0,    FQuerySchemaId=null,                                   FQuerySchemaLocked=0,    FReplaceByChildren=0, FSubMenuRoutine='',   FSubMenuSource='MenuTable', FTabTitle=null,              FTabTitleSource='PageTitle', FTreeLevel=3, FTreeSerial='002.003.025',         FType='Function';



-- TcKnowledge 
alter table TcKnowledge add column FIndex int;
alter table TcKnowledge add column FParentId uuid;
alter table TcKnowledge add column FTreeLevel int;
alter table TcKnowledge add column FTreeSerial varchar(100);
alter table TcKnowledge add column F_IDNumber varchar(15);
alter table TcKnowledge add column F_Publish timestamp;

update TsUnit set FSupportEqualQuery = 1, FSupportSort = 1, FSupportBusinessLog = 0, FSupportDataPrivilege = 0 where FId='f3ae5199-fcbb-425a-b879-7eec4c7e846c';
insert into TsField set FId='f6b3f036-d530-4091-bbdc-6738c138504e', FUnitId='f3ae5199-fcbb-425a-b879-7eec4c7e846c', FName='F_IDNumber',                FTitle='流水編號',             FType='InputBox-Text',       FSize=15,      FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null,                     FRelationTable=null,                          FRelationCapacity=null, FRelationId=null,                                   FSelectListFilterSql=null,                                                                                                 FSourceType='local',    FJoinField=null, FSourceField=null, FSource='',                                                                                                   FColSpan=1, FRowSpan=1,  FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,     FHint='',         FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql='',                                                                                                   FSelectListVariableFilterSql='',   FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='30404e8e-5b41-43c9-98d5-80dd257fff7f', FUnitId='f3ae5199-fcbb-425a-b879-7eec4c7e846c', FName='F_Publish',                 FTitle='發布時間',             FType='DateBox-DateTime',    FSize=null,    FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null,                     FRelationTable=null,                          FRelationCapacity=null, FRelationId=null,                                   FSelectListFilterSql=null,                                                                                                 FSourceType='local',    FJoinField=null, FSourceField=null, FSource='',                                                                                                   FColSpan=1, FRowSpan=1,  FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,     FHint='',         FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql='',                                                                                                   FSelectListVariableFilterSql='',   FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;

java setOrderFields('f3ae5199-fcbb-425a-b879-7eec4c7e846c', 'F_IDNumber', '1');

insert into TsScript set FId='c7749795-feff-4f53-8262-0fe7624247ff', FIndex=2,    FPageId='52dcedf0-fe15-4261-ab6f-4cc81bb9aac4', FUrl='custom/tbb/page/js/KnowView.js';
insert into TsScript set FId='19667e6a-c6a3-4692-80dd-112477fabddc', FIndex=3,    FPageId='52dcedf0-fe15-4261-ab6f-4cc81bb9aac4', FUrl='custom/tbb/page/js/Satisfc.js';
insert into TsScript set FId='a3a421bc-04b4-4a46-91ad-d942fe71cf2a', FIndex=4,    FPageId='52dcedf0-fe15-4261-ab6f-4cc81bb9aac4', FUrl='custom/tbb/page/js/KnowViewDiv.js';
insert into TsScript set FId='38803408-e1b1-4b96-84ba-7e3aaebcb55a', FIndex=2,    FPageId='d81081e1-7520-4856-af68-3e1d77b62815', FUrl='custom/tbb/page/js/Knowlege.js';

java setEditFields('5a7f0bf1-5fca-4c4a-9f6e-3827ffbc71ee', 'FName,FCreateDepartmentId,FCreateUserId,FPublicType,FStatus,FKnowledgeCatalogIds,FContent,FStartDate,FEndDate,FTimeType,FRemindCycle,FModifyComment,FUserId,FDepartmentId,FPublicRange,F_Publish');
java setEditFields('dd991f5d-7fcf-4153-9415-3e0f2ab990e8', 'FDayReadCount,FCreateDepartmentId,FName,FCreateUserId,FCreateTime,FReadRate,FAttachmentCount,FDepartmentId,FUserId,FPublicType,FKeyword,FEndDate,FStartDate,FType,FKnowledgeCatalogIds,FContent,FMonthReadCount,FYearReadCount,FWeekReadCount,FQuarterReadCount,FEffectTime,FTimeType,FRemindCycle,FNotRead,FProblem,FUpdateTime,FLanguage,FNextUpdateDate,FStatus,FTotalReadCount,FUpdateDepartmentId,FUpdateUserId,FModifyComment,FPublicRange,F_Publish');

java setListFields('9ecc0496-5f08-4a9f-b030-9bd595394c0f', 'F_IDNumber,FNotRead,FName,FAttachmentCount,FKnowledgeCatalogIds,FLanguage,FType,FStatus,FTimeType,FStartDate,FEndDate,FTotalReadCount,FReadRate');

insert into TsViewItemButton set FId='e691da52-8945-4e48-8103-4a60e5957308', FName='我要評分',   FViewItemId='43e46f18-eb46-472c-a663-33ffcb9d3100', FCode='Score',        FEventHandler='KnowView.doLoad()',                                                  FIndex=7, FVisibleCondition=null, FEnableCondition=null;

java setImportTemplateFields('f3ae5199-fcbb-425a-b879-7eec4c7e846c', 'FContent,FEndDate,FKnowledgeCatalogIds,FLanguage,FName,FRemindCycle,FRemindDuration,FReplyRemindCount,FStartDate,FTimeType,FType,FUserId,F_IDNumber');

insert into TsCondition set FId='aa39e9db-40c4-48b2-9955-1e7dcb8c2468', FUnitId='f3ae5199-fcbb-425a-b879-7eec4c7e846c';
insert into TsCondition set FId='88a093cb-b06e-4008-8a1e-eecbf4e36acf', FUnitId='f3ae5199-fcbb-425a-b879-7eec4c7e846c';
insert into TsCondition set FId='81527d80-1605-43b8-8080-350d12857f92', FUnitId='f3ae5199-fcbb-425a-b879-7eec4c7e846c';

-- TcCallLog 
alter table TcCallLog add column U_OpenFormYN varchar(20);
alter table TcCallLog add column U_InterestsInform varchar(20);
alter table TcCallLog add column U_ImportantNote varchar(1000);
alter table TcCallLog add column U_Forms varchar(10);
alter table TcCallLog add column U_FPID varchar(20);
alter table TcCallLog add column CustomerID varchar(20);
create table TpmTBBCallLogForm (FEntityId uuid, FValue varchar(100));
create index IpmTBBCallLogForm1 on TpmTBBCallLogForm (FEntityId);
create index IpmTBBCallLogForm2 on TpmTBBCallLogForm (FEntityId, FValue);

update TsUnit set FIsFullTextSearch = 1 where FId='5d6b7749-a28f-496b-9eff-524cb20474fc';
insert into TsField set FId='83da3354-ab42-0148-2af7-ffffff15ea42', FUnitId='5d6b7749-a28f-496b-9eff-524cb20474fc', FName='CustomerID',        FTitle='身分證號(新)',     FType='InputBox-Text',       FSize=20,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='0800c056-5000-6b20-a50b-157e5d68eac0', FUnitId='5d6b7749-a28f-496b-9eff-524cb20474fc', FName='U_Forms',           FTitle='表單',             FType='MultiCheckBox',       FSize=10,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId='ad7a100f-cbbb-0360-6bd9-ffffff1574b9', FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable='TpmTBBCallLogForm', FRelationCapacity=20,   FRelationId=null, FSelectListFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='83da33de-2ef3-0708-e6de-ffffff15b12e', FUnitId='5d6b7749-a28f-496b-9eff-524cb20474fc', FName='U_FPID',            FTitle='身分證',           FType='InputBox-Text',       FSize=20,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType='ServerValue',      FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='ad7a100f-cbbb-0348-2685-ffffff1574f9', FUnitId='5d6b7749-a28f-496b-9eff-524cb20474fc', FName='U_ImportantNote',   FTitle='重要記事',         FType='TextBox',             FSize=1000, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=3, FRowSpan=3, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='ad7a100f-cbbb-0368-9f51-ffffff1574f9', FUnitId='5d6b7749-a28f-496b-9eff-524cb20474fc', FName='U_InterestsInform', FTitle='權益告知',         FType='RadioBox',            FSize=20,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId='ad7a100f-cbbb-0350-b762-ffffff1574ba', FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='ad7a100f-cbbb-0338-693d-ffffff1574f9', FUnitId='5d6b7749-a28f-496b-9eff-524cb20474fc', FName='U_OpenFormYN',      FTitle='是否開立表單完成', FType='RadioBox',            FSize=20,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId='ad7a100f-cbbb-0350-5a41-ffffff1574ba', FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=2, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;

java setKeywordFields('5d6b7749-a28f-496b-9eff-524cb20474fc', 'FCallerPIN,FAni,FUserName,FUserId');

java setListFields('761c6e12-2247-4cdd-a0f9-93a4a4cb21bc', 'FContactId,FCallKind,FAni,FDnis,FDuration,U_ImportantNote,FStartTime,FEndTime,FWaitTime,FUserId,FPhonePlanTime,FPhonePlanName,FOutboundResult,FFailReason,FDepartmentId,FTargetCustomerId');
java setListFields('05a7f8f3-6644-43ed-b139-9707c2e0ffed', 'FDepartmentId,FContactId,FKnowledgeId,FStartTime,FEndTime,FWaitTime,FABNCounter,FInboundCounter,FWG,FCallerPIN,FUserId,U_FPID,FPhonePlanName,FPhonePlanTime');
java setListFields('401b5424-19a4-45c4-998d-e4932d67a829', 'FDepartmentId,FContactId,FKnowledgeId,FServiceRequestId,FStartTime,FEndTime,FWaitTime,FABNCounter,FInboundCounter,FWG,FGroupId,FPhonePlanTime,FUserId,U_FPID,FPhonePlanName');

insert into TsQuerySchema set FId='83da33b4-4fcf-2718-3e35-ffffff15caeb', FUnitId='5d6b7749-a28f-496b-9eff-524cb20474fc', FName='值機緣進線紀錄', FType='condition', FPublic=1, FTemp=0, FGlobalAutoQuery=0, FShare=0, FUserId='00000000-0000-0000-1002-000000000001', FConditionId='83da33b4-4fcf-0700-c14a-ffffff15caeb', FSqlSource='None', FSql='',   FIndex=6, FUpdateTime=timestamp('2017-06-16 10:21:35'), FOriginSchemaId=null, FVisible=1, FParentId=null;
insert into TsCondition set FId='83da33b4-4fcf-0700-c14a-ffffff15caeb', FUnitId='5d6b7749-a28f-496b-9eff-524cb20474fc';
insert into TsConditionPart set FId='83da33b4-4fcf-0f00-c14a-ffffff15caeb', FConditionId='83da33b4-4fcf-0700-c14a-ffffff15caeb', FGroupId=null, FIndex=1, FFieldName='FUserId',       FOperator='CurrentUser',        FValue=null,  FText=null;
insert into TsConditionPart set FId='83da33b4-4fcf-1700-c14a-ffffff15caeb', FConditionId='83da33b4-4fcf-0700-c14a-ffffff15caeb', FGroupId=null, FIndex=2, FFieldName='FStartTime',    FOperator='Current',            FValue='day', FText=null;
insert into TsConditionPart set FId='83da33b4-4fcf-1f00-c14a-ffffff15caeb', FConditionId='83da33b4-4fcf-0700-c14a-ffffff15caeb', FGroupId=null, FIndex=3, FFieldName='FEndTime',      FOperator='Current',            FValue='day', FText=null;

-- TcContact 
alter table TcContact add column U_CustName varchar(50);
alter table TcContact add column U_CustID varchar(10);
alter table TcContact add column U_CreditName varchar(50);
alter table TcContact add column U_CreditMobile varchar(20);
alter table TcContact add column U_CreditPhone varchar(30);
alter table TcContact add column U_CreditHomePhone varchar(30);
alter table TcContact add column U_CreditCompanyPhone varchar(30);
alter table TcContact add column U_CreditCustBirth varchar(10);
alter table TcContact add column U_CreditBranch varchar(20);
alter table TcContact add column U_CreditAccountNumber varchar(50);
alter table TcContact add column U_CreditAddress varchar(50);
alter table TcContact add column U_CreditEmail varchar(50);
alter table TcContact add column U_FinanceName varchar(50);
alter table TcContact add column U_FinanceMobile varchar(20);
alter table TcContact add column U_FinancePhone varchar(30);
alter table TcContact add column U_FinanceHomePhone varchar(30);
alter table TcContact add column U_FinanceCustBirth date;
alter table TcContact add column U_FinanceBranche varchar(50);
alter table TcContact add column U_FinanceAddress varchar(100);
alter table TcContact add column U_FinanceNewsLetter varchar(100);
alter table TcContact add column U_FaxHistory varchar(50);
alter table TcContact add column U_Dialogue varchar(10);
alter table TcContact add column U_CompanyName varchar(50);

create table TpTBBContact (FEntityId uuid, FValue varchar(100));
create index IpTBBContact1 on TpTBBContact (FEntityId);
create index IpTBBContact2 on TpTBBContact (FEntityId, FValue);

update TsUnit set FIsFullTextSearch=1 where FId='00000000-0000-0000-0001-020000001002';

insert into TsField set FId='83da333d-ac06-0350-cd78-ffffff16c6b7', FUnitId='00000000-0000-0000-0001-020000001002', FName='U_CompanyName',         FTitle='公司名稱',         FType='InputBox-Text',       FSize=50,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null,                                                            FSourceType='local', FJoinField=null,              FSourceField=null,               FSource=null,                                                                                                 FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null,                                                                        FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='ad7a100f-cbbb-0360-3faf-ffffff1574b5', FUnitId='00000000-0000-0000-0001-020000001002', FName='U_CreditAccountNumber', FTitle='扣款帳號',         FType='InputBox-Text',       FSize=50,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null,                                                            FSourceType='local', FJoinField=null,              FSourceField=null,               FSource=null,                                                                                                 FColSpan=2, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null,                                                                        FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='ad7a100f-cbbb-0330-34b9-ffffff1574b5', FUnitId='00000000-0000-0000-0001-020000001002', FName='U_CreditAddress',       FTitle='帳單地址',         FType='InputBox-Address',    FSize=50,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null,                                                            FSourceType='local', FJoinField=null,              FSourceField=null,               FSource=null,                                                                                                 FColSpan=3, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null,                                                                        FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='ad7a100f-cbbb-0328-079d-ffffff1574b5', FUnitId='00000000-0000-0000-0001-020000001002', FName='U_CreditBranch',        FTitle='來往分行',         FType='InputBox-Text',       FSize=20,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null,                                                            FSourceType='local', FJoinField=null,              FSourceField=null,               FSource=null,                                                                                                 FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null,                                                                        FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='ad7a100f-cbbb-0368-817c-ffffff1574b5', FUnitId='00000000-0000-0000-0001-020000001002', FName='U_CreditCompanyPhone',  FTitle='公司電話',         FType='InputBox-Text',       FSize=30,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null,                                                            FSourceType='local', FJoinField=null,              FSourceField=null,               FSource=null,                                                                                                 FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null,                                                                        FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='ad7a100f-cbbb-0300-f888-ffffff1574b5', FUnitId='00000000-0000-0000-0001-020000001002', FName='U_CreditCustBirth',     FTitle='客戶生日',         FType='InputBox-Text',       FSize=10,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null,                                                            FSourceType='local', FJoinField=null,              FSourceField=null,               FSource=null,                                                                                                 FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null,                                                                        FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='ad7a100f-cbbb-0350-1ec6-ffffff1574b5', FUnitId='00000000-0000-0000-0001-020000001002', FName='U_CreditEmail',         FTitle='E-Mail',           FType='InputBox-Email',      FSize=50,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null,                                                            FSourceType='local', FJoinField=null,              FSourceField=null,               FSource=null,                                                                                                 FColSpan=3, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null,                                                                        FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='ad7a100f-cbbb-0318-ac6d-ffffff1574b5', FUnitId='00000000-0000-0000-0001-020000001002', FName='U_CreditHomePhone',     FTitle='住家電話',         FType='InputBox-Phone',      FSize=30,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null,                                                            FSourceType='local', FJoinField=null,              FSourceField=null,               FSource=null,                                                                                                 FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null,                                                                        FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='ad7a100f-cbbb-0338-7f54-ffffff1574b5', FUnitId='00000000-0000-0000-0001-020000001002', FName='U_CreditMobile',        FTitle='手機(信用卡)',     FType='InputBox-Phone',      FSize=20,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null,                                                            FSourceType='local', FJoinField=null,              FSourceField=null,               FSource=null,                                                                                                 FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null,                                                                        FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='83da331a-bcea-0538-02fc-ffffff16d231', FUnitId='00000000-0000-0000-0001-020000001002', FName='U_CreditMobileTemp',    FTitle='手機(信用卡暫存)', FType='InputBox-Phone',      FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null,                                                            FSourceType='sql',   FJoinField=null,              FSourceField=null,               FSource='select FPhone from TcPhone where FUnitId = ''00000000-0000-0000-0001-020000001002'' and FEntityId = TcContact.FId and FEntityField = ''U_CreditMobileTemp''', FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null,                                                                        FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='ad7a100f-cbbb-0378-dc16-ffffff1574b5', FUnitId='00000000-0000-0000-0001-020000001002', FName='U_CreditName',          FTitle='姓名',             FType='InputBox-Text',       FSize=50,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null,                                                            FSourceType='local', FJoinField=null,              FSourceField=null,               FSource=null,                                                                                                 FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null,                                                                        FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='ad7a100f-cbbb-0340-d467-ffffff1574b5', FUnitId='00000000-0000-0000-0001-020000001002', FName='U_CreditPhone',         FTitle='來電電話',         FType='InputBox-Phone',      FSize=30,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null,                                                            FSourceType='local', FJoinField=null,              FSourceField=null,               FSource=null,                                                                                                 FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null,                                                                        FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='ad7a100f-cbbb-0310-347c-ffffff1574ad', FUnitId='00000000-0000-0000-0001-020000001002', FName='U_CustID',              FTitle='身分證字號',       FType='InputBox-Text',       FSize=10,   FVisible=1, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null,                                                            FSourceType='local', FJoinField=null,              FSourceField=null,               FSource=null,                                                                                                 FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null,                                                                        FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='ad7a100f-cbbb-0320-b06f-ffffff1574ad', FUnitId='00000000-0000-0000-0001-020000001002', FName='U_CustName',            FTitle='姓名',             FType='InputBox-Text',       FSize=50,   FVisible=1, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null,                                                            FSourceType='local', FJoinField=null,              FSourceField=null,               FSource=null,                                                                                                 FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null,                                                                        FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='0800c056-5000-6b20-a50b-157e602ba450', FUnitId='00000000-0000-0000-0001-020000001002', FName='U_Dialogue',            FTitle='對話特徵',         FType='MultiCheckBox',       FSize=10,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId='ad7a100f-cbbb-0358-429c-ffffff1574ad', FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable='TpTBBContact',              FRelationCapacity=10,   FRelationId=null, FSelectListFilterSql=null,                                                            FSourceType='local', FJoinField=null,              FSourceField=null,               FSource=null,                                                                                                 FColSpan=1, FRowSpan=1, FIsNewRow=1,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null,                                                                        FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='ad7a1060-086a-0240-5289-ffffff1579da', FUnitId='00000000-0000-0000-0001-020000001002', FName='U_FaxHistory',          FTitle='傳真紀錄',         FType='InputBox-Text',       FSize=50,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null,                                                            FSourceType='local', FJoinField=null,              FSourceField=null,               FSource=null,                                                                                                 FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null,                                                                        FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='ad7a100f-cbbb-0378-7a31-ffffff1574b6', FUnitId='00000000-0000-0000-0001-020000001002', FName='U_FinanceAddress',      FTitle='戶籍地址',         FType='InputBox-Address',    FSize=100,  FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null,                                                            FSourceType='local', FJoinField=null,              FSourceField=null,               FSource=null,                                                                                                 FColSpan=3, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null,                                                                        FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='ad7a100f-cbbb-0308-f824-ffffff1574b6', FUnitId='00000000-0000-0000-0001-020000001002', FName='U_FinanceBranche',      FTitle='往來分行',         FType='InputBox-Text',       FSize=50,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null,                                                            FSourceType='local', FJoinField=null,              FSourceField=null,               FSource=null,                                                                                                 FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null,                                                                        FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='ad7a100f-cbbb-0360-9b17-ffffff1574b6', FUnitId='00000000-0000-0000-0001-020000001002', FName='U_FinanceCustBirth',    FTitle='客戶生日',         FType='DateBox-Date',        FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null,                                                            FSourceType='local', FJoinField=null,              FSourceField=null,               FSource=null,                                                                                                 FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null,                                                                        FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='ad7a100f-cbbb-0358-c80e-ffffff1574b6', FUnitId='00000000-0000-0000-0001-020000001002', FName='U_FinanceHomePhone',    FTitle='住家電話',         FType='InputBox-Phone',      FSize=30,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null,                                                            FSourceType='local', FJoinField=null,              FSourceField=null,               FSource=null,                                                                                                 FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null,                                                                        FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='ad7a100f-cbbb-0330-aeee-ffffff1574b5', FUnitId='00000000-0000-0000-0001-020000001002', FName='U_FinanceMobile',       FTitle='手機(金融端)',     FType='InputBox-Phone',      FSize=20,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null,                                                            FSourceType='local', FJoinField=null,              FSourceField=null,               FSource=null,                                                                                                 FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null,                                                                        FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='83da331a-bcea-0550-b607-ffffff16d232', FUnitId='00000000-0000-0000-0001-020000001002', FName='U_FinanceMobileTemp',   FTitle='手機(金融端暫存)', FType='InputBox-Phone',      FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null,                                                            FSourceType='sql',   FJoinField=null,              FSourceField=null,               FSource='select FPhone from TcPhone where FUnitId = ''00000000-0000-0000-0001-020000001002'' and FEntityId = TcContact.FId and FEntityField = ''U_FinanceMobileTemp''', FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null,                                                                        FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='ad7a100f-cbbb-0318-12e2-ffffff1574b5', FUnitId='00000000-0000-0000-0001-020000001002', FName='U_FinanceName',         FTitle='姓名',             FType='InputBox-Text',       FSize=50,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null,                                                            FSourceType='local', FJoinField=null,              FSourceField=null,               FSource=null,                                                                                                 FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null,                                                                        FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='ad7a100f-cbbb-0330-d545-ffffff1574b6', FUnitId='00000000-0000-0000-0001-020000001002', FName='U_FinanceNewsLetter',   FTitle='通訊地址',         FType='InputBox-Address',    FSize=100,  FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null,                                                            FSourceType='local', FJoinField=null,              FSourceField=null,               FSource=null,                                                                                                 FColSpan=3, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null,                                                                        FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='ad7a100f-cbbb-0348-6efd-ffffff1574b5', FUnitId='00000000-0000-0000-0001-020000001002', FName='U_FinancePhone',        FTitle='來電電話',         FType='InputBox-Phone',      FSize=30,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null,                                                            FSourceType='local', FJoinField=null,              FSourceField=null,               FSource=null,                                                                                                 FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',   FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null,                                                                        FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;

java setQueryFormFields('00000000-0000-0000-0001-020000001002', 'U_CustID');
java setKeywordFields('00000000-0000-0000-0001-020000001002', 'U_CustID,FName,U_CreditName,U_FinanceName,U_CustName');

update TsSerialNumberPart set FLastSerial=10,   FLastSerialDate='20210518' where FId='8fee50ed-d6e6-44ed-9987-1929391b63f3';

insert into TsPage set FId='0ca0b23c-8478-6275-0a0b-15819f90d1c0', FName='金融端取得客戶資料',       FTitle='金融端取得客戶資料',   FCode='TBB.FinanceInfo',                   FPlatform='Computer', FType='Other',        FIcon='quicksilver/image/unit/New.gif',         FUrl='custom/tbb/page/tbbjs/FinanceInfo.jsp',        FActionMethodName=null,                                      FLoadHandler='FinanceInfo.doLoad',            FRelationId=null,                                   FUnitId='00000000-0000-0000-0001-020000001002', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FDialogWidth=null, FDialogHeight=null, FHasViewFrame=0,    FQueryOnLoad=null, FQuerySchemaId=null, FQueryFormAutoQuery=0,    FVisible=1, FDescription='',   FDialogMaximized=0,    FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments='',   FVisibleCondition=null,                                 FEditId='4e9b96a5-4c20-42a0-8929-d83efc27af4e', FFormColumnCount=null;
insert into TsPage set FId='0ca0b23c-8478-155c-c101-158238728fd0', FName='信用卡端取得客戶資料',     FTitle='信用卡端取得客戶資料', FCode='TBB.CreditCardsInfo',               FPlatform='Computer', FType='Other',        FIcon='quicksilver/image/unit/New.gif',         FUrl='custom/tbb/page/tbbjs/CreditCardsInfo.jsp',    FActionMethodName=null,                                      FLoadHandler='CreditCardsInfo.doLoad',        FRelationId=null,                                   FUnitId='00000000-0000-0000-0001-020000001002', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FDialogWidth=null, FDialogHeight=null, FHasViewFrame=0,    FQueryOnLoad=null, FQuerySchemaId=null, FQueryFormAutoQuery=0,    FVisible=1, FDescription='',   FDialogMaximized=0,    FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments='',   FVisibleCondition=null,                                 FEditId='4e9b96a5-4c20-42a0-8929-d83efc27af4e', FFormColumnCount=null;

--金融端取得客戶資料
insert into TsScript set FId='0ca0b23c-8478-6275-0a0b-15819fa19ba0', FIndex=1, FPageId='0ca0b23c-8478-6275-0a0b-15819f90d1c0', FUrl='custom/tbb/page/tbbjs/FinanceInfo.js';
insert into TsToolItem set FId='0ca0b23c-8478-6275-0a0b-15819f989d60', FPageId='0ca0b23c-8478-6275-0a0b-15819f90d1c0', FCode='Sure', FName='確定', FHint=null, FLabel=null, FType='Button', FAlign='right', FIndex=1, FWidth=null, FIcon=null, FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine='', FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='FinanceInfo.doChecked', FChartId=null;

--信用卡端取得客戶資料
insert into TsScript set FId='0ca0b23c-8478-155c-c101-1582388d8d50', FIndex=1, FPageId='0ca0b23c-8478-155c-c101-158238728fd0', FUrl='custom/tbb/page/tbbjs/CreditCardsInfo.js';
insert into TsToolItem set FId='0ca0b23c-8478-155c-c101-15823887f380', FPageId='0ca0b23c-8478-155c-c101-158238728fd0', FCode='Sure', FName='確定', FHint=null, FLabel=null, FType='Button', FAlign='right', FIndex=1, FWidth=null, FIcon=null, FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine='', FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='CreditCardsInfo.doChecked', FChartId=null;

insert into TsScript set FId='ad7a100a-92cb-0040-6988-ffffff157435', FIndex=1, FPageId='477b5ef2-141f-46a3-b965-3e2a428a0fd7', FUrl='custom/tbb/page/tbbjs/TBBContactForm.js';
insert into TsScript set FId='0ca0b23c-8478-fe70-bd00-1581dfaa67e0', FIndex=3, FPageId='477b5ef2-141f-46a3-b965-3e2a428a0fd7', FUrl='custom/tbb/page/tbbjs/UCustID.js';
insert into TsToolItem set FId='ad7a100a-92cb-0040-c151-ffffff157434', FPageId='477b5ef2-141f-46a3-b965-3e2a428a0fd7', FCode='DebitCust',     FName='金融端取得客戶資料',     FHint=null, FLabel=null, FType='Button',      FAlign='left',  FIndex=1,  FWidth=null, FIcon='quicksilver/image/unit/New.gif', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine='',                                                                                                   FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='TBBContactForm.doFinanceQuery("TVO3MBBT")', FChartId=null;
insert into TsToolItem set FId='ad7a100a-92cb-0078-aa63-ffffff157434', FPageId='477b5ef2-141f-46a3-b965-3e2a428a0fd7', FCode='CreditCust',    FName='信用卡端取得客戶資料',   FHint=null, FLabel=null, FType='Button',      FAlign='left',  FIndex=2,  FWidth=null, FIcon='quicksilver/image/unit/New.gif', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine='',                                                                                                   FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='TBBContactForm.doCreditCardsQuery("NB02")', FChartId=null;
insert into TsToolItem set FId='ad7a100a-92cb-0010-776e-ffffff157434', FPageId='477b5ef2-141f-46a3-b965-3e2a428a0fd7', FCode='GetForms',      FName='索取各項表格(含申請書)', FHint=null, FLabel=null, FType='ComboButton', FAlign='left',  FIndex=6,  FWidth=null, FIcon='quicksilver/image/unit/New.gif', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource='Sql',          FDictionaryId=null, FSubItemRoutine='select FId as FCode, FName  from TcDocument where FDocumentCatalogNames=''索取各項表格(含申請書)'' order by FName asc', FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='TBBContactForm.doOpenUGetForms',            FChartId=null;
insert into TsToolItem set FId='ad7a100a-92cb-0068-d3a3-ffffff157434', FPageId='477b5ef2-141f-46a3-b965-3e2a428a0fd7', FCode='DebitBusiness', FName='金融端業務',             FHint=null, FLabel=null, FType='ComboButton', FAlign='left',  FIndex=7,  FWidth=null, FIcon='quicksilver/image/unit/New.gif', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource='SubItemTable', FDictionaryId=null, FSubItemRoutine='',                                                                                                   FVisibleCondition=null, FEnableCondition=null, FHandleType='None',       FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='',                                          FChartId=null;
insert into TsToolItem set FId='ad7a100f-cbbb-0300-9bb3-ffffff1574d1', FPageId='477b5ef2-141f-46a3-b965-3e2a428a0fd7', FCode='Common',        FName='共用表單',               FHint=null, FLabel=null, FType='ComboButton', FAlign='left',  FIndex=9,  FWidth=null, FIcon='quicksilver/image/unit/New.gif', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource='SubItemTable', FDictionaryId=null, FSubItemRoutine='',                                                                                                   FVisibleCondition=null, FEnableCondition=null, FHandleType='None',       FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='',                                          FChartId=null;
insert into TsToolItem set FId='ad7a100f-cbbb-0340-1c5f-ffffff1574ff', FPageId='477b5ef2-141f-46a3-b965-3e2a428a0fd7', FCode='CreditLoss',    FName='信用卡掛失',             FHint=null, FLabel=null, FType='Button',      FAlign='left',  FIndex=10, FWidth=null, FIcon='quicksilver/image/unit/New.gif', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine='',                                                                                                   FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='TBBContactForm.doOpenUCreditLoss',          FChartId=null;
insert into TsToolItem set FId='83da33bd-d798-0038-021a-ffffff15c38b', FPageId='477b5ef2-141f-46a3-b965-3e2a428a0fd7', FCode='UNoReceive',    FName='未收到帳單查詢',         FHint=null, FLabel=null, FType='Button',      FAlign='left',  FIndex=11, FWidth=null, FIcon='quicksilver/image/unit/New.gif', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine='',                                                                                                   FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='TBBContactForm.doOpenUNoReceive',           FChartId=null;

insert into TsToolSubItem set FId='ad7a100a-92cb-0038-51af-ffffff157434', FToolItemId='ad7a100a-92cb-0068-d3a3-ffffff157434', FCode='TBB.UDepositInquire',   FName='存款查詢',                       FExpandMode='None', FIndex=45, FIcon='quicksilver/image/unit/New.gif',  FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='TBBContactForm.doOpenUDepositInquire',   FChartId=null;
insert into TsToolSubItem set FId='ad7a100a-92cb-0078-dbb6-ffffff157434', FToolItemId='ad7a100a-92cb-0068-d3a3-ffffff157434', FCode='TBB.UBasicInformation', FName='基本資料',                       FExpandMode='None', FIndex=46, FIcon='quicksilver/image/unit/New.gif',  FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='TBBContactForm.doOpenUBasicInformation', FChartId=null;
insert into TsToolSubItem set FId='ad7a100a-92cb-0058-83be-ffffff157434', FToolItemId='ad7a100a-92cb-0068-d3a3-ffffff157434', FCode='TBB.UCardDetail',       FName='發卡明細查詢',                   FExpandMode='None', FIndex=47, FIcon='quicksilver/image/unit/New.gif',  FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='TBBContactForm.doOpenUCardDetail',       FChartId=null;
insert into TsToolSubItem set FId='ad7a100f-cbbb-0308-2653-ffffff1574ff', FToolItemId='ad7a100a-92cb-0068-d3a3-ffffff157434', FCode='TBB.UDebitLoss',        FName='金融端掛失',                     FExpandMode='None', FIndex=63, FIcon='quicksilver/image/unit/New.gif',  FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='TBBContactForm.doOpenUDebitLoss',        FChartId=null;
insert into TsToolSubItem set FId='ad7a100f-cbbb-0320-14b1-ffffff1574f9', FToolItemId='ad7a100f-cbbb-0300-9bb3-ffffff1574d1', FCode='TBB.m12111A',           FName='預借現金密碼函',                 FExpandMode='None', FIndex=49, FIcon=null,                              FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='TBBContactForm.doOpenFormm12111A',       FChartId=null;
insert into TsToolSubItem set FId='ad7a100f-cbbb-0320-c9b7-ffffff1574f9', FToolItemId='ad7a100f-cbbb-0300-9bb3-ffffff1574d1', FCode='TBB.m12112A',           FName='轉介客戶抱怨單',                 FExpandMode='None', FIndex=50, FIcon=null,                              FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='TBBContactForm.doOpenFormm12112A',       FChartId=null;
insert into TsToolSubItem set FId='ad7a100f-cbbb-0378-e6bf-ffffff1574f9', FToolItemId='ad7a100f-cbbb-0300-9bb3-ffffff1574d1', FCode='TBB.m12113A',           FName='信用卡部轉介單',                 FExpandMode='None', FIndex=51, FIcon=null,                              FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='TBBContactForm.doOpenFormm12113A',       FChartId=null;
insert into TsToolSubItem set FId='ad7a100f-cbbb-0340-49c7-ffffff1574f9', FToolItemId='ad7a100f-cbbb-0300-9bb3-ffffff1574d1', FCode='TBB.m12114A',           FName='風管科客戶問題單',               FExpandMode='None', FIndex=52, FIcon=null,                              FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='TBBContactForm.doOpenFormm12114A',       FChartId=null;
insert into TsToolSubItem set FId='ad7a100f-cbbb-0358-e5cc-ffffff1574f9', FToolItemId='ad7a100f-cbbb-0300-9bb3-ffffff1574d1', FCode='TBB.m12115A',           FName='帳務組客戶問題單',               FExpandMode='None', FIndex=53, FIcon=null,                              FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='TBBContactForm.doOpenFormm12115A',       FChartId=null;
insert into TsToolSubItem set FId='ad7a100f-cbbb-0360-69d5-ffffff1574f9', FToolItemId='ad7a100f-cbbb-0300-9bb3-ffffff1574d1', FCode='TBB.m12117A',           FName='利息違約金減免單',               FExpandMode='None', FIndex=54, FIcon=null,                              FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='TBBContactForm.doOpenFormm12117A',       FChartId=null;
insert into TsToolSubItem set FId='ad7a100f-cbbb-0330-55dc-ffffff1574f9', FToolItemId='ad7a100f-cbbb-0300-9bb3-ffffff1574d1', FCode='TBB.m12118A',           FName='機場新貴通卡申請單',             FExpandMode='None', FIndex=55, FIcon=null,                              FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='TBBContactForm.doOpenFormm12118A',       FChartId=null;
insert into TsToolSubItem set FId='ad7a100f-cbbb-0300-99e6-ffffff1574f9', FToolItemId='ad7a100f-cbbb-0300-9bb3-ffffff1574d1', FCode='TBB.m12119A',           FName='信用卡來電分期及提前清償申請單', FExpandMode='None', FIndex=56, FIcon=null,                              FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='TBBContactForm.doOpenFormm12119A',       FChartId=null;
insert into TsToolSubItem set FId='ad7a100f-cbbb-0300-06f2-ffffff1574f9', FToolItemId='ad7a100f-cbbb-0300-9bb3-ffffff1574d1', FCode='TBB.m1211AA',           FName='基本資料變更申請單',             FExpandMode='None', FIndex=57, FIcon=null,                              FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='TBBContactForm.doOpenFormm1211AA',       FChartId=null;
insert into TsToolSubItem set FId='ad7a100f-cbbb-0328-45fb-ffffff1574f9', FToolItemId='ad7a100f-cbbb-0300-9bb3-ffffff1574d1', FCode='TBB.m1211BA',           FName='機場停車預約單',                 FExpandMode='None', FIndex=58, FIcon=null,                              FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='TBBContactForm.doOpenFormm1211BA',       FChartId=null;
insert into TsToolSubItem set FId='ad7a100f-cbbb-0350-b400-ffffff1574fa', FToolItemId='ad7a100f-cbbb-0300-9bb3-ffffff1574d1', FCode='TBB.m1211CA',           FName='調閱帳單',                       FExpandMode='None', FIndex=59, FIcon=null,                              FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='TBBContactForm.doOpenFormm1211CA',       FChartId=null;
insert into TsToolSubItem set FId='ad7a100f-cbbb-0300-3c78-ffffff157606', FToolItemId='ad7a100f-cbbb-0300-9bb3-ffffff1574d1', FCode='TBB.m12116A',           FName='信用卡額度調整單',               FExpandMode='None', FIndex=64, FIcon=null,                              FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='TBBContactForm.doOpenFormm12116A',       FChartId=null;

java setFormFields('4f650a4a-571a-4847-8a69-f4bcb7cc27ed', '基本資訊', '1f74ce45-c0b8-427c-9d31-67b558224e74', null, 'U_CustName,U_CustID,FTitle,U_Dialogue,FBusinessPhone', '客戶信用卡基本資料', 'ffffff15-74b6-cb90-500b-bbcb0f107aad', '1f74ce45-c0b8-427c-9d31-67b558224e74', 'U_CreditName,U_CreditMobile,U_CreditPhone,U_CreditHomePhone,U_CreditCompanyPhone,U_CreditCustBirth,U_CreditBranch,U_CreditAddress,U_CreditEmail,U_CreditMobileTemp', '客戶金融端基本資料', 'ffffff15-74b6-cb90-5013-bbcb0f107aad', '1f74ce45-c0b8-427c-9d31-67b558224e74', 'U_FinanceName,U_FinanceMobile,U_FinancePhone,U_FinanceHomePhone,U_FinanceCustBirth,U_FinanceAddress,U_FinanceNewsLetter,U_FinanceMobileTemp', '其他', 'ffffff15-74b6-cb90-501b-bbcb0f107aad', '1f74ce45-c0b8-427c-9d31-67b558224e74', 'FNote', '私人資訊', 'f3c1c46b-924d-44b7-9a2b-dc81f87986a9', null, 'FContactGroupName,FNickname,FLanguage,FBirthday,FAge,FBloodType,FMsn,FGender,FMarriage,FHobby,FEducationRecord,FHomeAddress,FHomePhone,FPrivateEmailAddress', '管理', '4b297eb1-4a93-42bc-abb7-c69e55b024b6', null, 'FCreateTime,FUpdateTime,FCreateUserId,FUpdateUserId,FCreateDepartmentId,FUpdateDepartmentId,FContactGroupId', '登入資訊', '42c45d31-305a-4d5d-8fd2-13c3bd1e13d8', null, 'FLoginAble,FLoginMail');
java setFormFields('53c48602-7c0b-46ea-9265-ee4a1819bee7', 'FUpdatePhoneField,FUpdatePhoneOld,FUpdatePhoneNew,U_CustID');
java setFormFields('20fd1648-b585-4240-b260-ee76a41a30df', 'FUpdatePhoneField,FUpdatePhoneOld,U_CustID');
java setFormFields('d1a24935-e11a-47cb-80f4-7a2bc9461815', '基本信息', '89361871-54c4-40e4-8faa-8b6701bc3d6f', null, 'FMobile,FPrivateEmailAddress,FGender,FBirthday,U_CustID', '归户信息', 'c5d5e1b7-18e1-4e79-8bfa-c21e5aa08093', null, 'FContactGroupId');
java setFormFields('42555a6f-a52a-47cb-b9f3-5acce826284f', 'FLoginMail,FLoginNewPwd,FLoginCheckPwd,U_CustID');

java setListFields('46581f90-f948-4569-996e-327d6e7002ed', 'FCreateTime,FNote,U_CustID,U_CreditMobile,U_FinanceMobile');
java setListFields('94a8d0b1-feff-4ca3-ba71-b25d440c7ce9', 'FName,FDuty,U_CustID,U_CreditMobile,U_FinanceMobile');
java setListFields('0697d8fd-ec4e-41dd-bd94-8bc7fdbd20bb', 'FSerialNumber,FName,FUserId,FDuty,FIsPersonalCustomer,U_CustID,U_CreditMobile,U_FinanceMobile');
java setImportTemplateFields('00000000-0000-0000-0001-020000001002', 'FMsn,FNote,FUpdatePhoneField,FHobby,FContactGroupName,FMarriageDate,FCustomerId,FNickname,FAge,FCompanyRole,FCompanyId,FBusinessAddress,FLeaderId,FBirthday,FIsMainRole,FMarriage,FPrivateEmailAddress,FRegion,FProvince,FDepartment,FConstellation,FEducationRecord,FBloodType,FEnglishName,FPostcode,FPicture,FTitle,FDuty,FHomePhone,FStatus,FFirstName,FGender,FLastName,FLanguage,FAccessDenied,FBusinessPhone,FMobile,FBusinessEmailAddress,FCountry,FCity,FHomeAddress,FUserId');

insert into TsCondition set FId='83da331a-bcea-0520-9a23-ffffff16d155', FUnitId='00000000-0000-0000-0001-020000001002';
insert into TsConditionPart set FId='83da331a-bcea-0518-9b23-ffffff16d155', FConditionId='83da331a-bcea-0520-9a23-ffffff16d155', FGroupId=null, FIndex=1, FFieldName='U_CustID',      FOperator='Equal',              FValue='N124276571', FText=null;




