
--金融卡發卡主檔

ALTER TABLE tpTBBUATMCardDetail ADD U_PHPW varchar(1);
ALTER TABLE tpTBBUATMCardDetail ADD U_AOPLMT varchar(7);
ALTER TABLE tpTBBUATMCardDetail ADD U_AODLMT varchar(7);

insert into TsField set FId='0800c056-5000-2070-e80e-17c34b234be0', FUnitId='2eda0929-0c00-8f3a-bb07-179eabb6da30', FName='U_AODLMT',        FTitle='簽帳卡每日限額',               FType='InputBox-Text',       FSize=7,     FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',                            FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null, FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='0800c056-5000-2070-e80e-17c34b050290', FUnitId='2eda0929-0c00-8f3a-bb07-179eabb6da30', FName='U_AOPLMT',        FTitle='消費扣款每日限額',             FType='InputBox-Text',       FSize=7,     FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',                            FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null, FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='0800c056-5000-2070-e80e-17c34af11100', FUnitId='2eda0929-0c00-8f3a-bb07-179eabb6da30', FName='U_PHPW',          FTitle='全行收付',                     FType='InputBox-Text',       FSize=1,     FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint='',                            FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null, FMobileListFormat=null, FFollowingField=null, FParentField=null;

java setFormFields('2eda0929-0c00-8f3a-bb07-179eabb77e80', '基本資訊', '2eda0929-0c00-8f3a-bb07-179eabb780d0', null, 'U_ACNO,U_Inquiry', '查詢結果', '179ef7f4-2980-0ebe-60e9-000c2909da2e', '2eda0929-0c00-8f3a-bb07-179eabb780d0', 'U_FUserId,U_UID,U_PHPW,U_CardNo,U_CardNum,U_Status,U_IsApplyTrans,U_IsApplyNoDep,U_ApplyInDraw,U_AOPLMT,U_AODLMT,U_PINCNT,U_TRINCT,U_ABAVCT,U_ABAVCTX,U_MEGECT,U_ABUSCT,U_ABUSCTX,U_EndYM,U_GRPCOD,U_VSEXPYM,U_VSDBYN,U_SMART,U_PACNO,U_ABKEYTP,U_BRHACC,U_Inquiry3,U_Inquiry2,U_Inquiry4,U_Result,U_ResultExplain', '金融卡發卡歷史查詢', '179efcde-5f90-0ebe-60e9-000c2909da2e', '2eda0929-0c00-8f3a-bb07-179eabb780d0', 'U_A011Grid', '金融卡發卡明細查詢', '179efd07-bda0-0ebe-60e9-000c2909da2e', '2eda0929-0c00-8f3a-bb07-179eabb780d0', 'U_A012Grid');


--網銀主檔

ALTER TABLE tpTBBEBankingInfo ADD U_BRHTMP varchar(3);
ALTER TABLE tpTBBEBankingInfo ADD U_CHEERER varchar(6);

insert into TsField set FId='0800c056-5000-2070-e80e-17c34d6af990', FUnitId='ec9b8729-0c00-c076-4804-17a17bd04880', FName='U_BRHTMP',       FTitle='網銀服務鍵機行',                   FType='InputBox-Text',       FSize=3,     FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null,          FDefaultValue=null, FHint='',                           FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null, FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='0800c056-5000-2070-e80e-17c34d717f80', FUnitId='ec9b8729-0c00-c076-4804-17a17bd04880', FName='U_CHEERER',      FTitle='網路銀行推廣行員',                 FType='InputBox-Text',       FSize=6,     FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                        FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null,          FDefaultValue=null, FHint='',                           FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null, FMobileListFormat=null, FFollowingField=null, FParentField=null;

java setFormFields('ec9b8729-0c00-c076-4804-17a17bd100f0', '基本資訊', 'ec9b8729-0c00-c076-4804-17a17bd103a0', null, 'U_UID,U_CQ13Button', '網路銀行轉帳主檔', '17a17c05-4740-0448-76c0-000c29879bec', 'ec9b8729-0c00-c076-4804-17a17bd103a0', 'U_TSFCNT,U_LOGINDTM,U_IsEmail,U_STSCOD1_CQ13,U_STSCOD2_CQ13,U_CHGMAIL,U_SETNBP1,U_SETNBP2,U_PWDDTTM,U_CNTNBW1,U_CNTNBW2,U_TYPE,U_APLCODB,U_APLCODA,U_USERID,U_UIDSTC,U_E_BILL,U_UIDCNT,U_APLBRH,U_BRHTMP,U_SNHKEY,U_TRAACN,U_CHGPWDT,U_DATAPL,U_DATDLT,U_CHEERER,U_UPDFLG,U_OPCODE,U_CNMARK,U_PASCODE,U_CORFLAG,U_SECCODE,U_IDNCOD,U_CQ14Button,U_CQ15Button', '網路銀行轉帳延伸檔', '17a17ec9-8990-0448-76c0-000c29879bec', 'ec9b8729-0c00-c076-4804-17a17bd103a0', 'U_Grid', '行動銀行快速登入記錄檔', '17a180e0-8320-0448-76c0-000c29879bec', 'ec9b8729-0c00-c076-4804-17a17bd103a0', 'U_QKLINDTTM,U_QLGIDT,U_QCKSTAT,U_QTRNDT,U_QTRSTAT,U_MOBYN,U_QSMLDT,U_QSMSTAT,U_MOBCODE,U_MOBDATE,U_BIOME,U_VERYN,U_VERTYPE,U_VERNUM1,U_VERDATE1,U_STSCOD1,U_VERNUM2,U_VERDATE2,U_STSCOD2,U_VERNUM3,U_VERDATE3,U_STSCOD3,U_VERNUM4,U_VERDATE4,U_STSCOD4,U_VERNUM5,U_VERDATE5,U_STSCOD5,U_VERNUM6,U_VERDATE6,U_STSCOD6,U_VERNUM7,U_VERDATE7,U_STSCOD7,U_VERNUM8,U_VERDATE8,U_STSCOD8');

