--Cti.SipxFaxOutBox-------------------------------------------------------------
delete from TsScript where FId='0100c056-5000-d64f-7804-17b05d8a0e90';
insert into TsScript set FId='0800c056-5000-2d63-2309-17b290902eb0', FIndex=2, FPageId='daf6641b-0ea1-49b0-92da-6d89f9b552e7', FUrl='custom/tbb/page/sipxfaxoutbox/SipxFaxForm.js';

-- 字典 信用卡掛失-掛失告知 ----
update TsDictionaryItem set FDictionaryId='ad7a100f-cbbb-0310-c771-ffffff1574ab', FEnabled=1, FIndex=10, FParentValue=null, FText='VD卡限掛失當日到分行撤銷掛失，請本人攜帶ID、原留印鑑到分行辦理撤掛(非營業時間，於次營業日到分行撤銷掛失)', FValue='9' where FId='ad7a100f-cbbb-3310-93c5-ffffff1574ab';


-- 調閱帳單TBB.m1211CA ----
update TsUnit set FCode='TBB.m1211CA', FName='調閱帳單', FIcon='quicksilver/image/unit/13.png', FEditId='541c707d-79dd-4dbb-85fc-1a214fd5fce4', FModuleId='00000000-0000-0000-0008-020000000010', FOpenMode='Tab', FIsTreeStructure=0, FMaxTreeLevel=null, FIsSlaveUnit=0, FMasterUnitId=null, FSupportWorkflow=1, FSupportUser=1, FSupportDepartment=0, FSupportEditType=0, FSupportAttachment=1, FSupportDataPrivilege=1, FSupportVersion=1, FSupportBusinessLog=1, FSupportNote=0, FSupportSort=0, FSupportPrivilegeField=1, FIsFullTextSearch=1, FSearchAttachment=0, FSupportEqualQuery=1, FUseSystemI18nTable=0, FExtraQueryResultLimit=0, FRecordCreateInfo=1, FRecordUpdateInfo=0, FRecordDeleteInfo=0, FOpenViewPageFirst=0, FDataSource='default', FTable='TBBm1211C', FKeyField='FId', FKeyType='Uuid', FNameField='FName', FMasterField=null, FHomeClassName=null, FDaoClassName=null, FServiceClassName=null, FActionClassName=null, FWebServiceUniqueField=null, FUnitFilterSql='', FBusinessFilterSql='', FDescription='', FOpenViewPageCondition=null, FViewPageConditionForList=null, FViewPageConditionForLink=null, FBigIcon=null, FIsTreeCheckPrivilege=0, FApiClassName=null, FApiEnabled=0, FSupportSynonyms=0 where FId='9fab5436-78b6-4b43-b32d-6ce5c2d925bd';


-- 金融端掛失TBB.UDebitLoss ----

update TsField set FAlwaysBringDataToClient=0, FColSpan=1, FCustomData='',   FDefaultValue=null,            FDefaultValueType=null, FDictionaryId='46f8c7c1-7cea-48dc-8343-1acb6da1b7fb', FEntityUnitId=null,   FFilterByRole=0, FFollowingField=null, FHint='', FIsNewRow=0,    FJoinField=null, FLabelColor=null, FListAlign='default', FListWidth=100, FLocalTextField=null, FMobileListFormat=null, FName='U_LossKind',            FParentField=null, FQueryable=1, FReadOnly=1, FRelationCapacity=null, FRelationId=null, FRelationTable=null,                  FRequired=0, FRowSpan=1, FScale=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSize=20,   FSource=null, FSourceField=null, FSourceType='local',    FSupportI18n=0,    FSupportLocalText=0,    FTitle='掛失種類(舊)',        FType='RadioBox',            FUnitId='facf418f-d079-4741-be22-35352ced706f', FValidation=null, FVisible=1, FWebServiceCreateField=null, FWebServiceItemQueryField=null, FWebServiceListQueryField=null where FId='09f88712-40ed-49ea-8c4f-73ff92e4fc83';
update TsField set FAlwaysBringDataToClient=0, FColSpan=1, FCustomData='',   FDefaultValue=null,            FDefaultValueType=null, FDictionaryId=null,                                   FEntityUnitId=null,                                   FFilterByRole=0, FFollowingField=null, FHint='提醒：COMBO卡信用卡端要至財金掛失', FIsNewRow=1,    FJoinField=null, FLabelColor=null, FListAlign='default', FListWidth=100, FLocalTextField=null, FMobileListFormat=null, FName='U_Remind',              FParentField=null, FQueryable=1, FReadOnly=0, FRelationCapacity=null, FRelationId=null, FRelationTable=null,                  FRequired=0, FRowSpan=1, FScale=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSize=null, FSource=null, FSourceField=null, FSourceType='constant', FSupportI18n=0,    FSupportLocalText=0,    FTitle='提醒',                FType='Label',               FUnitId='facf418f-d079-4741-be22-35352ced706f', FValidation=null, FVisible=1, FWebServiceCreateField=null, FWebServiceItemQueryField=null, FWebServiceListQueryField=null where FId='24c4a703-8a98-443d-b3c9-acbcd9e1a417';
