--TBB.stopcardapply-------------------------------------------------------------
UPDATE TwVersion set FStatus='Expired' where FId='c5cfcd29-0c00-a07a-b805-17bcedc7a440';

java setListFields('0100c056-5000-ca09-510a-179e48558410', 'F_CreditCardNo,U_eCardNo,F_AppendName,F_Identify,U_Control,U_StopDate,U_IsStages,U_CardStop,U_Return,FUserId,U_Check1,U_CheckAgent');

insert into TwVersion set FBusinessLogCode=null, FBusinessLogDescription=null, FDepartmentId=null, FDescription=null, FEntityEventCode=null, FId='c5cfcd29-0c00-a07a-b805-17bddfe163c0', FNotice='{"useDefaultFinishNotice":true,"useDefaultTerminateNotice":true,"useDefaultWorkItemNotice":true,"useDefaultFinishMedia":true,"useDefaultWorkItemMedia":true,"useDefaultTerminateMedia":true}', FReleaseTime=timestamp('2021-09-13 15:10:38'), FRelevantData='[]', FStatus='Active', FVersion=6, FWorkflowId='0100c056-5000-ca09-510a-179e55fab6b0';
insert into TwNode set FAutoCompleteMode='None', FAutoCompleteResult=null, FAutoCompleteTimeLength=null, FAutoCompleteTimeType=null, FAutoFinish=null, FBatchPassResult=null, FCode='AGENT',  FDeputeHours=null, FDeputeMode='DefaultHours', FExpectedResult=null, FId='c5cfcd29-0c00-a07a-b805-17bddfe2ba10', FInstant=0,    FJoinCondition='',   FJoinConditionType=null, FJoinMode='Single', FMultiWorkItem=0,    FName='臺企銀客服一線退回修改', FPageLoadHandler=null, FParticipant='{"source":"Initiator"}',                                                                             FPrivilegeId=null, FSupportBatchPass=0,    FSupportClone=0,    FSupportTransfer=0,    FType='Manual', FUrl=null, FUrlType='EntityInfo', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0', FX=10, FY=1;
insert into TwNode set FAutoCompleteMode='None', FAutoCompleteResult=null, FAutoCompleteTimeLength=null, FAutoCompleteTimeType=null, FAutoFinish=null, FBatchPassResult=null, FCode='AGENT1', FDeputeHours=null, FDeputeMode='DefaultHours', FExpectedResult=null, FId='c5cfcd29-0c00-a07a-b815-17bddfe2bd00', FInstant=0,    FJoinCondition='',   FJoinConditionType=null, FJoinMode='Single', FMultiWorkItem=0,    FName='臺企銀客服一線(覆核)',   FPageLoadHandler=null, FParticipant='{"source":"Field","value":"entity.U_CheckAgent"}',                                                   FPrivilegeId=null, FSupportBatchPass=0,    FSupportClone=0,    FSupportTransfer=0,    FType='Manual', FUrl=null, FUrlType='EntityInfo', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0', FX=5,  FY=6;
insert into TwNode set FAutoCompleteMode='None', FAutoCompleteResult=null, FAutoCompleteTimeLength=null, FAutoCompleteTimeType=null, FAutoFinish=null, FBatchPassResult=null, FCode='AGENT2', FDeputeHours=null, FDeputeMode='DefaultHours', FExpectedResult=null, FId='c5cfcd29-0c00-a07a-b805-17bddfe2bff0', FInstant=0,    FJoinCondition='',   FJoinConditionType=null, FJoinMode='Single', FMultiWorkItem=0,    FName='臺企銀客服二線',         FPageLoadHandler=null, FParticipant='{"source":"List","value":[{"text":"臺企銀客服二線","type":"Role","value":"d1a4bd4e-87d0-4833-a596-5adcdbee4abd"}]}', FPrivilegeId=null, FSupportBatchPass=0,    FSupportClone=0,    FSupportTransfer=0,    FType='Manual', FUrl=null, FUrlType='EntityInfo', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0', FX=10, FY=11;
insert into TwNode set FAutoCompleteMode='None', FAutoCompleteResult=null, FAutoCompleteTimeLength=null, FAutoCompleteTimeType=null, FAutoFinish=null, FBatchPassResult=null, FCode='AGENT3', FDeputeHours=null, FDeputeMode='DefaultHours', FExpectedResult=null, FId='c5cfcd29-0c00-a07a-b805-17bddfe25010', FInstant=0,    FJoinCondition='',   FJoinConditionType=null, FJoinMode='Single', FMultiWorkItem=0,    FName='臺企銀作業科人員',       FPageLoadHandler=null, FParticipant='{"source":"List","value":[{"text":"臺企銀作業科人員1","type":"Role","value":"bc5fab26-3887-4d6d-b81c-380e04cf1b06"}]}', FPrivilegeId=null, FSupportBatchPass=0,    FSupportClone=0,    FSupportTransfer=0,    FType='Manual', FUrl=null, FUrlType='EntityInfo', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0', FX=18, FY=11;
insert into TwNode set FAutoCompleteMode='None', FAutoCompleteResult=null, FAutoCompleteTimeLength=null, FAutoCompleteTimeType=null, FAutoFinish=null, FBatchPassResult=null, FCode='AGENT4', FDeputeHours=null, FDeputeMode='DefaultHours', FExpectedResult=null, FId='c5cfcd29-0c00-a07a-b805-17bddfe2c7a0', FInstant=0,    FJoinCondition='',   FJoinConditionType=null, FJoinMode='Single', FMultiWorkItem=0,    FName='臺企銀客服一線',         FPageLoadHandler=null, FParticipant='{"source":"Initiator"}',                                                                             FPrivilegeId=null, FSupportBatchPass=0,    FSupportClone=0,    FSupportTransfer=0,    FType='Manual', FUrl=null, FUrlType='EntityInfo', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0', FX=25, FY=11;
insert into TwNode set FAutoCompleteMode='None', FAutoCompleteResult=null, FAutoCompleteTimeLength=null, FAutoCompleteTimeType=null, FAutoFinish=1,    FBatchPassResult=null, FCode='Agree1', FDeputeHours=null, FDeputeMode='DefaultHours', FExpectedResult=null, FId='c5cfcd29-0c00-a07a-b805-17bddfe2b310', FInstant=null, FJoinCondition='',   FJoinConditionType=null, FJoinMode='Single', FMultiWorkItem=null, FName='同意',                   FPageLoadHandler=null, FParticipant=null,                                                                                                 FPrivilegeId=null, FSupportBatchPass=null, FSupportClone=null, FSupportTransfer=null, FType='Auto',   FUrl=null, FUrlType=null,         FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0', FX=5,  FY=11;
insert into TwNode set FAutoCompleteMode='None', FAutoCompleteResult=null, FAutoCompleteTimeLength=null, FAutoCompleteTimeType=null, FAutoFinish=1,    FBatchPassResult=null, FCode='Agree2', FDeputeHours=null, FDeputeMode='DefaultHours', FExpectedResult=null, FId='c5cfcd29-0c00-a07a-b805-17bddfe2b610', FInstant=null, FJoinCondition='',   FJoinConditionType=null, FJoinMode='Single', FMultiWorkItem=null, FName='同意',                   FPageLoadHandler=null, FParticipant=null,                                                                                                 FPrivilegeId=null, FSupportBatchPass=null, FSupportClone=null, FSupportTransfer=null, FType='Auto',   FUrl=null, FUrlType=null,         FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0', FX=14, FY=11;
insert into TwNode set FAutoCompleteMode='None', FAutoCompleteResult=null, FAutoCompleteTimeLength=null, FAutoCompleteTimeType=null, FAutoFinish=1,    FBatchPassResult=null, FCode='Agree3', FDeputeHours=null, FDeputeMode='DefaultHours', FExpectedResult=null, FId='c5cfcd29-0c00-a07a-b805-17bddfe2b7f0', FInstant=null, FJoinCondition='',   FJoinConditionType=null, FJoinMode='Single', FMultiWorkItem=null, FName='同意',                   FPageLoadHandler=null, FParticipant=null,                                                                                                 FPrivilegeId=null, FSupportBatchPass=null, FSupportClone=null, FSupportTransfer=null, FType='Auto',   FUrl=null, FUrlType=null,         FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0', FX=22, FY=11;
insert into TwNode set FAutoCompleteMode='None', FAutoCompleteResult=null, FAutoCompleteTimeLength=null, FAutoCompleteTimeType=null, FAutoFinish=1,    FBatchPassResult=null, FCode='Back1',  FDeputeHours=null, FDeputeMode='DefaultHours', FExpectedResult=null, FId='c5cfcd29-0c00-a07a-b805-17bddfe29f90', FInstant=null, FJoinCondition='',   FJoinConditionType=null, FJoinMode='Single', FMultiWorkItem=null, FName='退回',                   FPageLoadHandler=null, FParticipant=null,                                                                                                 FPrivilegeId=null, FSupportBatchPass=null, FSupportClone=null, FSupportTransfer=null, FType='Auto',   FUrl=null, FUrlType=null,         FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0', FX=5,  FY=1;
insert into TwNode set FAutoCompleteMode='None', FAutoCompleteResult=null, FAutoCompleteTimeLength=null, FAutoCompleteTimeType=null, FAutoFinish=1,    FBatchPassResult=null, FCode='Back2',  FDeputeHours=null, FDeputeMode='DefaultHours', FExpectedResult=null, FId='c5cfcd29-0c00-a07a-b805-17bddfe27530', FInstant=null, FJoinCondition='',   FJoinConditionType=null, FJoinMode='Single', FMultiWorkItem=null, FName='退回',                   FPageLoadHandler=null, FParticipant=null,                                                                                                 FPrivilegeId=null, FSupportBatchPass=null, FSupportClone=null, FSupportTransfer=null, FType='Auto',   FUrl=null, FUrlType=null,         FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0', FX=10, FY=6;
insert into TwNode set FAutoCompleteMode='None', FAutoCompleteResult=null, FAutoCompleteTimeLength=null, FAutoCompleteTimeType=null, FAutoFinish=1,    FBatchPassResult=null, FCode='Back3',  FDeputeHours=null, FDeputeMode='DefaultHours', FExpectedResult=null, FId='c5cfcd29-0c00-a07a-b805-17bddfe2ae40', FInstant=null, FJoinCondition='',   FJoinConditionType=null, FJoinMode='Single', FMultiWorkItem=null, FName='退回',                   FPageLoadHandler=null, FParticipant=null,                                                                                                 FPrivilegeId=null, FSupportBatchPass=null, FSupportClone=null, FSupportTransfer=null, FType='Auto',   FUrl=null, FUrlType=null,         FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0', FX=14, FY=6;
insert into TwNode set FAutoCompleteMode=null,   FAutoCompleteResult=null, FAutoCompleteTimeLength=null, FAutoCompleteTimeType=null, FAutoFinish=null, FBatchPassResult=null, FCode='END',    FDeputeHours=null, FDeputeMode=null,           FExpectedResult=null, FId='c5cfcd29-0c00-a07a-b805-17bddfe1ed60', FInstant=null, FJoinCondition='',   FJoinConditionType=null, FJoinMode='Single', FMultiWorkItem=null, FName='結束',                   FPageLoadHandler=null, FParticipant=null,                                                                                                 FPrivilegeId=null, FSupportBatchPass=null, FSupportClone=null, FSupportTransfer=null, FType='End',    FUrl=null, FUrlType=null,         FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0', FX=29, FY=1;
insert into TwNode set FAutoCompleteMode=null,   FAutoCompleteResult=null, FAutoCompleteTimeLength=null, FAutoCompleteTimeType=null, FAutoFinish=null, FBatchPassResult=null, FCode='END2',   FDeputeHours=null, FDeputeMode=null,           FExpectedResult=null, FId='c5cfcd29-0c00-a07a-b805-17bddfe24740', FInstant=null, FJoinCondition='',   FJoinConditionType=null, FJoinMode='Single', FMultiWorkItem=null, FName='結束',                   FPageLoadHandler=null, FParticipant=null,                                                                                                 FPrivilegeId=null, FSupportBatchPass=null, FSupportClone=null, FSupportTransfer=null, FType='End',    FUrl=null, FUrlType=null,         FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0', FX=29, FY=11;
insert into TwNode set FAutoCompleteMode=null,   FAutoCompleteResult=null, FAutoCompleteTimeLength=null, FAutoCompleteTimeType=null, FAutoFinish=null, FBatchPassResult=null, FCode='START',  FDeputeHours=null, FDeputeMode=null,           FExpectedResult=null, FId='c5cfcd29-0c00-a07a-b805-17bddfe1b9a0', FInstant=null, FJoinCondition=null, FJoinConditionType=null, FJoinMode=null,     FMultiWorkItem=null, FName='開始',                   FPageLoadHandler=null, FParticipant=null,                                                                                                 FPrivilegeId=null, FSupportBatchPass=null, FSupportClone=null, FSupportTransfer=null, FType='Start',  FUrl=null, FUrlType=null,         FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0', FX=1,  FY=6;
insert into TwLine set FCode='LINE-1',  FCondition='',                           FConditionType=null,         FDefault=1, FFrom='START',  FId='c5cfcd29-0c00-a07a-b805-17bddfe2f4e0', FJumpResult=null, FName='提交', FRoutes=null, FSupportJump=0,    FTo='AGENT1', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwLine set FCode='LINE-10', FCondition='${AGENT3Result}=="Back"',    FConditionType='JavaScript', FDefault=0, FFrom='AGENT3', FId='c5cfcd29-0c00-a07a-b815-17bddfe2f8f0', FJumpResult=null, FName='打回', FRoutes=null, FSupportJump=0,    FTo='Back3',  FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwLine set FCode='LINE-11', FCondition='',                           FConditionType=null,         FDefault=1, FFrom='Back2',  FId='c5cfcd29-0c00-a07a-b805-17bddfe2fae0', FJumpResult=null, FName='退回', FRoutes='[]', FSupportJump=0,    FTo='AGENT',  FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwLine set FCode='LINE-12', FCondition='',                           FConditionType=null,         FDefault=1, FFrom='Back3',  FId='c5cfcd29-0c00-a07a-b805-17bddfe30e60', FJumpResult=null, FName='退回', FRoutes='[]', FSupportJump=0,    FTo='AGENT',  FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwLine set FCode='LINE-13', FCondition='',                           FConditionType=null,         FDefault=1, FFrom='Agree1', FId='c5cfcd29-0c00-a07a-b815-17bddfe30e60', FJumpResult=null, FName='同意', FRoutes='[]', FSupportJump=0,    FTo='AGENT2', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwLine set FCode='LINE-14', FCondition='',                           FConditionType=null,         FDefault=1, FFrom='Agree2', FId='c5cfcd29-0c00-a07a-b805-17bddfe30f60', FJumpResult=null, FName='同意', FRoutes='[]', FSupportJump=0,    FTo='AGENT3', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwLine set FCode='LINE-15', FCondition=null,                         FConditionType=null,         FDefault=1, FFrom='Agree3', FId='c5cfcd29-0c00-a07a-b815-17bddfe30f60', FJumpResult=null, FName=null,   FRoutes='[]', FSupportJump=null, FTo='AGENT4', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwLine set FCode='LINE-16', FCondition='${AGENTResult}==''Submit''', FConditionType='JavaScript', FDefault=0, FFrom='AGENT',  FId='c5cfcd29-0c00-a07a-b805-17bddfe31040', FJumpResult=null, FName='提交', FRoutes='[]', FSupportJump=0,    FTo='AGENT1', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwLine set FCode='LINE-2',  FCondition='${AGENTResult}=="Discard"',  FConditionType='JavaScript', FDefault=0, FFrom='AGENT',  FId='c5cfcd29-0c00-a07a-b805-17bddfe2f5e0', FJumpResult=null, FName='作廢', FRoutes=null, FSupportJump=0,    FTo='END',    FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwLine set FCode='LINE-3',  FCondition='${AGENT1Result}=="Back"',    FConditionType='JavaScript', FDefault=0, FFrom='AGENT1', FId='c5cfcd29-0c00-a07a-b805-17bddfe2f9e0', FJumpResult=null, FName='打回', FRoutes=null, FSupportJump=0,    FTo='Back1',  FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwLine set FCode='LINE-4',  FCondition='',                           FConditionType=null,         FDefault=1, FFrom='Back1',  FId='c5cfcd29-0c00-a07a-b815-17bddfe2f9e0', FJumpResult=null, FName='退回', FRoutes=null, FSupportJump=0,    FTo='AGENT',  FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwLine set FCode='LINE-5',  FCondition='${AGENT1Result}=="Agree"',   FConditionType='JavaScript', FDefault=0, FFrom='AGENT1', FId='c5cfcd29-0c00-a07a-b805-17bddfe2f6d0', FJumpResult=null, FName='同意', FRoutes=null, FSupportJump=0,    FTo='Agree1', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwLine set FCode='LINE-6',  FCondition='${AGENT3Result}=="Agree"',   FConditionType='JavaScript', FDefault=0, FFrom='AGENT3', FId='c5cfcd29-0c00-a07a-b805-17bddfe2f8f0', FJumpResult=null, FName='同意', FRoutes=null, FSupportJump=0,    FTo='Agree3', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwLine set FCode='LINE-7',  FCondition='${AGENT2Result}=="Back"',    FConditionType='JavaScript', FDefault=0, FFrom='AGENT2', FId='c5cfcd29-0c00-a07a-b805-17bddfe2f800', FJumpResult=null, FName='打回', FRoutes=null, FSupportJump=0,    FTo='Back2',  FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwLine set FCode='LINE-8',  FCondition='${AGENT2Result}=="Agree"',   FConditionType='JavaScript', FDefault=0, FFrom='AGENT2', FId='c5cfcd29-0c00-a07a-b815-17bddfe2f800', FJumpResult=null, FName='同意', FRoutes=null, FSupportJump=0,    FTo='Agree2', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwLine set FCode='LINE-9',  FCondition='${AGENT4Result}=="Agree"',   FConditionType='JavaScript', FDefault=0, FFrom='AGENT4', FId='c5cfcd29-0c00-a07a-b805-17bddfe31130', FJumpResult=null, FName='同意', FRoutes=null, FSupportJump=0,    FTo='END2',   FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwButton set FCode='Agree',   FCommentRequired=0, FEntityEventCode=null, FHandleType='Default', FIcon=null, FId='c5cfcd29-0c00-a07a-b805-17bddfe25500', FIndex=1, FName='同意', FNodeId='c5cfcd29-0c00-a07a-b805-17bddfe25010', FPageId=null, FParentId=null, FSaveForm=null, FScript=null, FType='Button';
insert into TwButton set FCode='Back',    FCommentRequired=0, FEntityEventCode=null, FHandleType='Default', FIcon=null, FId='c5cfcd29-0c00-a07a-b805-17bddfe25bc0', FIndex=2, FName='打回', FNodeId='c5cfcd29-0c00-a07a-b805-17bddfe25010', FPageId=null, FParentId=null, FSaveForm=0,    FScript='',   FType='Button';
insert into TwButton set FCode='Submit',  FCommentRequired=0, FEntityEventCode=null, FHandleType='Default', FIcon=null, FId='c5cfcd29-0c00-a07a-b805-17bddfe2bae0', FIndex=1, FName='提交', FNodeId='c5cfcd29-0c00-a07a-b805-17bddfe2ba10', FPageId=null, FParentId=null, FSaveForm=0,    FScript='',   FType='Button';
insert into TwButton set FCode='Discard', FCommentRequired=0, FEntityEventCode=null, FHandleType='Default', FIcon=null, FId='c5cfcd29-0c00-a07a-b805-17bddfe2bc00', FIndex=2, FName='作廢', FNodeId='c5cfcd29-0c00-a07a-b805-17bddfe2ba10', FPageId=null, FParentId=null, FSaveForm=0,    FScript='',   FType='Button';
insert into TwButton set FCode='Agree',   FCommentRequired=0, FEntityEventCode=null, FHandleType='Default', FIcon=null, FId='c5cfcd29-0c00-a07a-b805-17bddfe2bde0', FIndex=1, FName='同意', FNodeId='c5cfcd29-0c00-a07a-b815-17bddfe2bd00', FPageId=null, FParentId=null, FSaveForm=null, FScript=null, FType='Button';
insert into TwButton set FCode='Back',    FCommentRequired=0, FEntityEventCode=null, FHandleType='Default', FIcon=null, FId='c5cfcd29-0c00-a07a-b805-17bddfe2bee0', FIndex=2, FName='打回', FNodeId='c5cfcd29-0c00-a07a-b815-17bddfe2bd00', FPageId=null, FParentId=null, FSaveForm=0,    FScript='',   FType='Button';
insert into TwButton set FCode='Agree',   FCommentRequired=0, FEntityEventCode=null, FHandleType='Default', FIcon=null, FId='c5cfcd29-0c00-a07a-b805-17bddfe2c0d0', FIndex=1, FName='同意', FNodeId='c5cfcd29-0c00-a07a-b805-17bddfe2bff0', FPageId=null, FParentId=null, FSaveForm=null, FScript=null, FType='Button';
insert into TwButton set FCode='Back',    FCommentRequired=0, FEntityEventCode=null, FHandleType='Default', FIcon=null, FId='c5cfcd29-0c00-a07a-b805-17bddfe2c1d0', FIndex=2, FName='打回', FNodeId='c5cfcd29-0c00-a07a-b805-17bddfe2bff0', FPageId=null, FParentId=null, FSaveForm=0,    FScript='',   FType='Button';
insert into TwButton set FCode='Agree',   FCommentRequired=0, FEntityEventCode=null, FHandleType='Default', FIcon=null, FId='c5cfcd29-0c00-a07a-b805-17bddfe2d7b0', FIndex=1, FName='同意', FNodeId='c5cfcd29-0c00-a07a-b805-17bddfe2c7a0', FPageId=null, FParentId=null, FSaveForm=null, FScript=null, FType='Button';
insert into TwEvent set FContent='{FStatus:"END1"}',                                                                                   FEntityEventCode=null, FHandleType='UpdateEntity', FId='c5cfcd29-0c00-a07a-b805-17bddfe24620', FIndex=1, FNodeId='c5cfcd29-0c00-a07a-b805-17bddfe1ed60', FNoticeId=null,                                   FNoticeRecipients='[]',                                                                                    FOccasion='OnActivityCreateAfter', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwEvent set FContent='{FStatus:"End"}',                                                                                    FEntityEventCode=null, FHandleType='UpdateEntity', FId='c5cfcd29-0c00-a07a-b805-17bddfe24f20', FIndex=1, FNodeId='c5cfcd29-0c00-a07a-b805-17bddfe24740', FNoticeId=null,                                   FNoticeRecipients='[]',                                                                                    FOccasion='OnActivityCreateAfter', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwEvent set FContent='{FStatus:"Audit3"}',                                                                                 FEntityEventCode=null, FHandleType='UpdateEntity', FId='c5cfcd29-0c00-a07a-b805-17bddfe261e0', FIndex=1, FNodeId='c5cfcd29-0c00-a07a-b805-17bddfe25010', FNoticeId=null,                                   FNoticeRecipients='[]',                                                                                    FOccasion='OnActivityCreateAfter', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwEvent set FContent='',                                                                                                   FEntityEventCode=null, FHandleType='SendNotice',   FId='c5cfcd29-0c00-a07a-b805-17bddfe28ba0', FIndex=1, FNodeId='c5cfcd29-0c00-a07a-b805-17bddfe27530', FNoticeId='0100c056-5000-870f-8204-17a36e715a70', FNoticeRecipients='[{"type":"Initiator"}]',                                                                FOccasion='OnActivityCreateAfter', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwEvent set FContent='',                                                                                                   FEntityEventCode=null, FHandleType='SendNotice',   FId='c5cfcd29-0c00-a07a-b805-17bddfe2ad50', FIndex=1, FNodeId='c5cfcd29-0c00-a07a-b805-17bddfe29f90', FNoticeId='0100c056-5000-870f-8204-17a36e3bcc90', FNoticeRecipients='[{"type":"Initiator"}]',                                                                FOccasion='OnActivityCreateAfter', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwEvent set FContent='',                                                                                                   FEntityEventCode=null, FHandleType='SendNotice',   FId='c5cfcd29-0c00-a07a-b805-17bddfe2b230', FIndex=1, FNodeId='c5cfcd29-0c00-a07a-b805-17bddfe2ae40', FNoticeId='0100c056-5000-870f-8204-17a36e8b8ec0', FNoticeRecipients='[{"type":"Initiator"}]',                                                                FOccasion='OnActivityCreateAfter', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwEvent set FContent='',                                                                                                   FEntityEventCode=null, FHandleType='SendNotice',   FId='c5cfcd29-0c00-a07a-b805-17bddfe2b540', FIndex=1, FNodeId='c5cfcd29-0c00-a07a-b805-17bddfe2b310', FNoticeId='0100c056-5000-785f-0408-17a37eddc280', FNoticeRecipients='[{"type":"Initiator"},{"type":"Role","value":"d1a4bd4e-87d0-4833-a596-5adcdbee4abd"}]', FOccasion='OnActivityCreateAfter', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwEvent set FContent='',                                                                                                   FEntityEventCode=null, FHandleType='SendNotice',   FId='c5cfcd29-0c00-a07a-b805-17bddfe2b700', FIndex=1, FNodeId='c5cfcd29-0c00-a07a-b805-17bddfe2b610', FNoticeId='0100c056-5000-785f-0408-17a37f0cc2c0', FNoticeRecipients='[{"type":"Initiator"},{"type":"Role","value":"bc5fab26-3887-4d6d-b81c-380e04cf1b06"}]', FOccasion='OnActivityCreateAfter', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwEvent set FContent='',                                                                                                   FEntityEventCode=null, FHandleType='SendNotice',   FId='c5cfcd29-0c00-a07a-b805-17bddfe2b8f0', FIndex=1, FNodeId='c5cfcd29-0c00-a07a-b805-17bddfe2b7f0', FNoticeId='0100c056-5000-785f-0408-17a37f4b2010', FNoticeRecipients='[{"type":"Initiator"}]',                                                                FOccasion='OnActivityCreateAfter', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwEvent set FContent='{FStatus:"AgentSign1"}',                                                                             FEntityEventCode=null, FHandleType='UpdateEntity', FId='c5cfcd29-0c00-a07a-b805-17bddfe2bd00', FIndex=1, FNodeId='c5cfcd29-0c00-a07a-b805-17bddfe2ba10', FNoticeId=null,                                   FNoticeRecipients='[]',                                                                                    FOccasion='OnActivityCreateAfter', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwEvent set FContent='{FStatus:"AgentSign"}',                                                                              FEntityEventCode=null, FHandleType='UpdateEntity', FId='c5cfcd29-0c00-a07a-b815-17bddfe2bee0', FIndex=1, FNodeId='c5cfcd29-0c00-a07a-b815-17bddfe2bd00', FNoticeId=null,                                   FNoticeRecipients='[]',                                                                                    FOccasion='OnActivityCreateAfter', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwEvent set FContent='{FStatus:"Audit"}',                                                                                  FEntityEventCode=null, FHandleType='UpdateEntity', FId='c5cfcd29-0c00-a07a-b805-17bddfe2c6a0', FIndex=1, FNodeId='c5cfcd29-0c00-a07a-b805-17bddfe2bff0', FNoticeId=null,                                   FNoticeRecipients='[]',                                                                                    FOccasion='OnActivityCreateAfter', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwEvent set FContent='update TpTBBstopcardapply set U_Check2 =
(select twp.FUserId as FUserId  from  TwWorkItem tw 
left join  TwParticipant twp on twp.FWorkItemId = tw.FId
where tw.FEntityId = ${entity.FId} and tw.FActivityCode = ''AGENT2'' and tw.FStatus = ''Drawn'')
where FId = ${entity.FId}', FEntityEventCode=null, FHandleType='Sql',          FId='c5cfcd29-0c00-a07a-b815-17bddfe2c6a0', FIndex=2, FNodeId='c5cfcd29-0c00-a07a-b805-17bddfe2bff0', FNoticeId=null,                                   FNoticeRecipients='[]',                                                                                    FOccasion='OnWorkItemDrawAfter',   FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';
insert into TwEvent set FContent='{FStatus:"AgentSign"}',                                                                              FEntityEventCode=null, FHandleType='UpdateEntity', FId='c5cfcd29-0c00-a07a-b805-17bddfe2e180', FIndex=1, FNodeId='c5cfcd29-0c00-a07a-b805-17bddfe2c7a0', FNoticeId=null,                                   FNoticeRecipients='[]',                                                                                    FOccasion='OnActivityCreateAfter', FVersionId='c5cfcd29-0c00-a07a-b805-17bddfe163c0';

--/TBB.stopcardapply-------------------------------------------------------------



--TBB.m1211CA-------------------------------------------------------------------

UPDATE TsField set FTitle='帳單種類' where FId='0100c056-5000-7228-f90a-17a1298af420';

--/TBB.m1211CA-------------------------------------------------------------------



--TBB.UCardinformation----------------------------------------------------------
alter table tpTBBUCardinformation ADD U_PostAcct varchar(16);

alter table tpTBBUCardinformation ADD U_RIOPT varchar(1);

alter table tpTBBUCardinformation ADD U_CIOPT varchar(1);

alter table tpTBBUCardinformation ADD U_LATECHGOPT varchar(1);

alter table tpTBBUCardinformation ADD U_CSHLIMIT varchar(9);

alter table tpTBBUCardinformation ADD U_CURRDUE double;

UPDATE TsField set FIsNewRow=0 where FId='2eda0929-0c00-9c71-8308-17a3792f76f0';

UPDATE TsField set FIsNewRow=0 where FId='2eda0929-0c00-9c71-8308-17a378f7ddb0';

UPDATE TsField set FIsNewRow=0 where FId='2eda0929-0c00-9c71-8308-17a377c15bb0';

UPDATE TsField set FIsNewRow=0 where FId='2eda0929-0c00-9c71-8308-17a377ba43a0';

UPDATE TsField set FIsNewRow=0 where FId='2eda0929-0c00-9c71-8308-17a3789d1d70'; 

UPDATE TsField set FIsNewRow=1 where FId='2eda0929-0c00-9c71-8308-17a37973a540';

UPDATE TsField set FIsNewRow=0 where FId='2eda0929-0c00-9c71-8308-17a3797b4620';

insert into TsField set FId='c5cfcd29-0c00-431c-dd02-17c262441db0', FUnitId='2eda0929-0c00-9c71-8308-17a3766ed360', FName='U_CIOPT',             FTitle='預借現金利息',            FType='InputBox-Text',       FSize=1,     FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,   FHint='',     FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null, FMobileListFormat=null, FFollowingField=null, FParentField=null;

UPDATE TsField set FIsNewRow=0 where FId='2eda0929-0c00-9c71-8308-17a379c29e40'; 

insert into TsField set FId='c5cfcd29-0c00-431c-dd02-17c2635dfc00', FUnitId='2eda0929-0c00-9c71-8308-17a3766ed360', FName='U_CSHLIMIT',          FTitle='預現額度',                FType='InputBox-Text',       FSize=9,     FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,   FHint='',     FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null, FMobileListFormat=null, FFollowingField=null, FParentField=null;

insert into TsField set FId='c5cfcd29-0c00-431c-dd02-17c2636e9ae0', FUnitId='2eda0929-0c00-9c71-8308-17a3766ed360', FName='U_CURRDUE',           FTitle='本期應繳',                FType='InputBox-Double',     FSize=null,  FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=1,    FListWidth=100, FListAlign='default', FScale=2,    FLabelColor=null, FDefaultValue=null,   FHint='',     FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null, FMobileListFormat=null, FFollowingField=null, FParentField=null;

insert into TsField set FId='c5cfcd29-0c00-431c-dd02-17c2631be3f0', FUnitId='2eda0929-0c00-9c71-8308-17a3766ed360', FName='U_LATECHGOPT',        FTitle='延遲繳款違約金',          FType='InputBox-Text',       FSize=1,     FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,   FHint='',     FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null, FMobileListFormat=null, FFollowingField=null, FParentField=null;


UPDATE TsField set FIsNewRow=0 where FId='2eda0929-0c00-9c71-8308-17a37a07ac90';

insert into TsField set FId='c5cfcd29-0c00-431c-dd02-17c2616cfa10', FUnitId='2eda0929-0c00-9c71-8308-17a3766ed360', FName='U_PostAcct',          FTitle='主帳號',                  FType='InputBox-Text',       FSize=16,    FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=1,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,   FHint='',     FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null, FMobileListFormat=null, FFollowingField=null, FParentField=null;

insert into TsField set FId='c5cfcd29-0c00-431c-dd02-17c2623ae640', FUnitId='2eda0929-0c00-9c71-8308-17a3766ed360', FName='U_RIOPT',             FTitle='購貨帳款利息',            FType='InputBox-Text',       FSize=1,     FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local',    FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=1,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,   FHint='',     FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null, FMobileListFormat=null, FFollowingField=null, FParentField=null;

java setFormFields('2eda0929-0c00-9c71-8308-17a376700400', '基本資訊', '2eda0929-0c00-9c71-8308-17a376700550', null, 'U_PageNum,U_ErrorCode,U_ErrorMemo,U_CardNum,U_Inquiry', '查詢結果', '17a37afa-2ec0-0883-719c-000c2909da2e', '2eda0929-0c00-9c71-8308-17a376700550', 'U_OCardNum,U_OCardType,U_Cardexpirydate,U_Cname,U_UID,U_Birthday,U_Ename,U_Cellphone,U_Email,U_PostAcct,U_Custnmbr,U_Corporate,U_BranchNo,U_BranchNops,U_Billprint,U_AuditorNo,U_Controlcode,U_Controlcodedate,U_OControlcode,U_OControlcodedate,U_Cardapproval,U_Cardmakingday,U_PA,U_Billing,U_Ddaacct,U_Type,U_ACHRTNMBR,U_Account,U_Withhold,U_Cusattributes,U_Payment,U_Accounttype,U_Dailycashadvance,U_CSHLIMIT,U_CURRDUE,U_Collection,U_Collectionaccount,U_RIOPT,U_CIOPT,U_LATECHGOPT,U_Savacct,U_Neweffect,U_Newcard,U_Purchase,U_Advance,U_Maintaindate,U_Rating0106,U_Rating0712,U_Rating1318,U_Rating1924');

java setImportTemplateFields('2eda0929-0c00-9c71-8308-17a3766ed360', 'U_CardType,FName,U_CardNum,U_Inquiry,U_PostAcct,U_CSHLIMIT,U_CURRDUE,U_RIOPT,U_CIOPT,U_LATECHGOPT,U_Rating0106,U_Rating0712,U_Rating1318,U_Rating1924');


UPDATE TsField set FVisible=0 where FId='2eda0929-0c00-9c71-8308-17a3773b3ce0';

java setImportTemplateFields('2eda0929-0c00-9c71-8308-17a3766ed360', 'FName,U_CardNum,U_Inquiry,U_PostAcct,U_CSHLIMIT,U_CURRDUE,U_RIOPT,U_CIOPT,U_LATECHGOPT,U_Rating0106,U_Rating0712,U_Rating1318,U_Rating1924');

--/TBB.UCardinformation----------------------------------------------------------


--TBB.URequestunpaid------------------------------------------------------------
UPDATE TsField set FVisible=0 where FId='2eda0929-0c00-2477-180e-17a1cf79d3d0';

java setImportTemplateFields('2eda0929-0c00-8d1e-9704-17a19b7f5e10', 'FName,U_CardNum,U_Inquiry,U_Grid');

delete from TsFieldGridColumn where FId='2eda0929-0c00-2477-180e-17a1cfe00cc0';

--/TBB.URequestunpaid------------------------------------------------------------