--TBB.FMan----------------------------------------------------------------------
update TsUnit set FCode='TBB.FMan', FName='評分', FIcon='quicksilver/image/unit/New.gif', FEditId='541c707d-79dd-4dbb-85fc-1a214fd5fce4', FModuleId='00000000-0000-0000-0008-020000000010', FOpenMode='System', FIsTreeStructure=0, FMaxTreeLevel=null, FIsSlaveUnit=0, FMasterUnitId=null, FSupportWorkflow=0, FSupportUser=0, FSupportDepartment=0, FSupportEditType=0, FSupportAttachment=0, FSupportDataPrivilege=0, FSupportVersion=0, FSupportBusinessLog=0, FSupportNote=0, FSupportSort=0, FSupportPrivilegeField=0, FIsFullTextSearch=0, FSearchAttachment=0, FSupportEqualQuery=0, FUseSystemI18nTable=0, FExtraQueryResultLimit=0, FRecordCreateInfo=0, FRecordUpdateInfo=0, FRecordDeleteInfo=0, FOpenViewPageFirst=0, FDataSource='default', FTable='TpTBBmFMan', FKeyField='FId', FKeyType='Uuid', FNameField='FName', FMasterField=null, FHomeClassName='com.chainsea.tbb.fman.FManHome', FDaoClassName='com.chainsea.tbb.fman.dao.impl.FManDaoImpl', FServiceClassName='com.chainsea.tbb.fman.service.impl.FManServiceImpl', FActionClassName='com.chainsea.tbb.fman.action.impl.FManActionImpl', FWebServiceUniqueField=null, FUnitFilterSql='', FBusinessFilterSql='', FDescription='', FOpenViewPageCondition=null, FViewPageConditionForList=null, FViewPageConditionForLink=null, FBigIcon='quicksilver/image/unit/New.gif', FIsTreeCheckPrivilege=null, FApiClassName=null, FApiEnabled=null, FSupportSynonyms=null where FId='ef13062d-bf9c-42c8-8183-cb3ed04f0faa';

-- TcCallLog 
java setFormFields('4f9a1eb1-cd28-4f45-b18b-8b2952a23e55', '基本資訊', 'f53e8a6e-8f8c-4f20-a857-0e3e40e8a35c', null, 'U_OpenFormYN,U_InterestsInform,U_ImportantNote,FPhonePlanName,FPhonePlanTime', '進線資訊', 'a624b295-db29-4b7c-b1c9-6e187e0a7fa0', null, 'FAni,FDnis,FWG,FABNCounter,FDesignationUser,FWGError,FIsComplaintCase,FInboundCounter,FObjectId,FUnitId,FWaitTime,FCallerPIN,FIsShortCall,FIsLongCall,FFailReason,FIsBeginner,FCallKind,FPId', '管理', '1a480dc3-372e-4ebd-8f71-9f0337ecc0b1', null, 'FEndTime,FStartTime,FDuration,FUserId,FDepartmentId,FOutboundResult,FProductCatalogId,FTargetCustomerId,FContactId,FLeadId');
java setOrderFields('5d6b7749-a28f-496b-9eff-524cb20474fc', 'FStartTime', '1');
java setImportTemplateFields('5d6b7749-a28f-496b-9eff-524cb20474fc', 'FUniqueId,FName,FSessionId,FGroupId,FCallStatus,FCallKind,FCustomerId,FTaskId,FObjectId,FPhonePlanTime,FPhonePlanName,FNote,FCallReplyStatus');

-- TcKnowledge 
java setQueryFormFields('f3ae5199-fcbb-425a-b879-7eec4c7e846c', 'FName,FKeyword,FKnowledgeCatalogIds');
java setKeywordFields('f3ae5199-fcbb-425a-b879-7eec4c7e846c', 'FName,FContent,FKeyword');
java setCopyIgnoreFields('f3ae5199-fcbb-425a-b879-7eec4c7e846c', 'FCreateDepartmentId,FCreateTime,FCreateUserId,FDailyReadCounts,FDayReadCount,FEffectTime,FId,FLanguageGroupId,FMonthReadCount,FNextUpdateDate,FQuarterReadCount,FReadRate,FStatus,FTotalReadCount,FUpdateDepartmentId,FUpdateTime,FUpdateUserId,FWeekReadCount,FYearReadCount');
java setFormFields('7520382a-0d9e-430f-8f04-3944f656db53', '基本資訊', 'f91141a9-effc-4c29-b53a-82bc026a32eb', null, 'FName,FKnowledgeCatalogIds,FLanguage,FUserId,FDepartmentId,FType,FStatus,F_Publish', '公開設置', 'ae4192b9-5132-467c-bdab-6d103827ad9f', 'f91141a9-effc-4c29-b53a-82bc026a32eb', 'FPublicType,FPublicRange', '時間與提醒', '05e4a7dc-1d0c-4db8-aaf1-71a504e300f5', 'f91141a9-effc-4c29-b53a-82bc026a32eb', 'FTimeType,FRemindCycle,FStartDate,FEndDate,FNextUpdateDate', '點閱', '40c56a1a-8536-42ba-8680-5f683aa1e1e3', 'f91141a9-effc-4c29-b53a-82bc026a32eb', 'FReadRate,FTotalReadCount,FDayReadCount,FWeekReadCount,FMonthReadCount,FQuarterReadCount,FYearReadCount', '內容', '03a2b5e3-ff53-411a-b8e3-c98ba690e02e', 'f91141a9-effc-4c29-b53a-82bc026a32eb', 'FKeyword,FContent', '管理', 'aea7c90c-0016-480d-869d-c2ef3cb6f99d', null, 'FCreateTime,FUpdateTime,FCreateUserId,FUpdateUserId,FCreateDepartmentId,FUpdateDepartmentId');
java setFormFields('fbb4e099-5375-406c-b356-522537c112b4', 'FModifyComment');
java setListFields('9149303e-5e56-495c-80f1-c52f9f5cb82c', 'FName,FStartDate,FEndDate,FNextUpdateDate,FNotRead,FStatus');
java setListFields('460ba35b-9935-4349-a07e-4eee7b2ffe49', 'FName,FKnowledgeCatalogIds,FLanguage,FType,FStatus,FNotRead');
java setDuplicationFields('7fe554f2-4f89-4dbe-8a87-26cda5c456a3', 'FLanguageGroupId,FLanguage');
java setDuplicationHintFields('7fe554f2-4f89-4dbe-8a87-26cda5c456a3', 'FName,FLanguage');

--Qs.User-----------------------------------------------------------------------
alter table TsUser add column FCreateUserId uuid;
alter table TsUser add column FCreateDepartmentId uuid;
alter table TsUser add column FCreateTime timestamp;
alter table TsUser add column FUpdateUserId uuid;
alter table TsUser add column FUpdateDepartmentId uuid;
alter table TsUser add column FUpdateTime timestamp;

update TsUnit set FCode='Qs.User', FName='員工', FIcon='quicksilver/image/unit/User.gif', FEditId='541c707d-79dd-4dbb-85fc-1a214fd5fce4', FModuleId='00000000-0000-0000-0008-990000000010', FOpenMode='System', FIsTreeStructure=0, FMaxTreeLevel=0, FIsSlaveUnit=0, FMasterUnitId=null, FSupportWorkflow=0, FSupportUser=0, FSupportDepartment=0, FSupportEditType=0, FSupportAttachment=0, FSupportDataPrivilege=0, FSupportVersion=0, FSupportBusinessLog=0, FSupportNote=0, FSupportSort=1, FSupportPrivilegeField=1, FIsFullTextSearch=0, FSearchAttachment=0, FSupportEqualQuery=0, FUseSystemI18nTable=0, FExtraQueryResultLimit=0, FRecordCreateInfo=1, FRecordUpdateInfo=1, FRecordDeleteInfo=0, FOpenViewPageFirst=0, FDataSource='default', FTable='TsUser', FKeyField='FId', FKeyType='Uuid', FNameField='FName', FMasterField=null, FHomeClassName='com.jeedsoft.quicksilver.user.UserHome', FDaoClassName='com.jeedsoft.quicksilver.user.dao.impl.UserDaoImpl', FServiceClassName='com.jeedsoft.quicksilver.user.service.impl.UserServiceImpl', FActionClassName='com.chainsea.ecp.user.action.impl.UserActionImpl', FWebServiceUniqueField=null, FUnitFilterSql='', FBusinessFilterSql='FEnabled=1', FDescription='', FOpenViewPageCondition=null, FViewPageConditionForList=null, FViewPageConditionForLink=null, FBigIcon='quicksilver/image/unit/User-64.png', FIsTreeCheckPrivilege=0, FApiClassName='com.jeedsoft.quicksilver.user.api.impl.UserApiImpl', FApiEnabled=1, FSupportSynonyms=0 where FId='00000000-0000-0000-0001-000000001002';

insert into TsField set FId='0100c056-5000-7937-390d-17a9931be420', FUnitId='00000000-0000-0000-0001-000000001002', FName='FCreateDepartmentId', FTitle='建立部門',     FType='EntityBox',           FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId='00000000-0000-0000-0001-000000001001', FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null,                                                                                                 FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null,                                 FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null, FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='0100c056-5000-7937-390d-17a9931be910', FUnitId='00000000-0000-0000-0001-000000001002', FName='FCreateTime',         FTitle='建立時間',     FType='DateBox-DateTime',    FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null,                                                                                                 FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=120, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null,                                 FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null, FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='0100c056-5000-7937-390d-17a9931bdb80', FUnitId='00000000-0000-0000-0001-000000001002', FName='FCreateUserId',       FTitle='建立者',       FType='EntityBox',           FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId='00000000-0000-0000-0001-000000001002', FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null,                                                                                                 FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=80,  FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null,                                 FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null, FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='0100c056-5000-7937-390d-17a9931bf670', FUnitId='00000000-0000-0000-0001-000000001002', FName='FUpdateDepartmentId', FTitle='最後修改部門', FType='EntityBox',           FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId='00000000-0000-0000-0001-000000001001', FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null,                                                                                                 FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null,                                 FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null, FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='0100c056-5000-7937-390d-17a9931bfbe0', FUnitId='00000000-0000-0000-0001-000000001002', FName='FUpdateTime',         FTitle='最後修改時間', FType='DateBox-DateTime',    FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null,                                                                                                 FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=120, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null,                                 FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null, FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
insert into TsField set FId='0100c056-5000-7937-390d-17a9931bf0a0', FUnitId='00000000-0000-0000-0001-000000001002', FName='FUpdateUserId',       FTitle='最後修改人',   FType='EntityBox',           FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId='00000000-0000-0000-0001-000000001002', FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null,                                                                                                 FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=80,  FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null,                                 FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null, FSelectListFilterSqlExceedable=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FAlwaysBringDataToClient=0, FDefaultValueType=null,               FMobileListFormat=null, FFollowingField=null, FParentField=null;
